
CREATE TABLE ACCESSION_CHARACTERISTICS
(
  ID                        NUMBER(10,2),
  OTHER_SURGICAL_PROCEDURE  VARCHAR2(255 BYTE)
);


CREATE UNIQUE INDEX PK_ACCESSION_CHARACTERISTICS ON ACCESSION_CHARACTERISTICS
(ID);


ALTER TABLE ACCESSION_CHARACTERISTICS ADD (
  CONSTRAINT PK_ACCESSION_CHARACTERISTICS PRIMARY KEY (ID));



