/*
 * MainFrame.java
 *
 * Created on May 16, 2006, 2:23 PM
 */

package edu.duke.cabig.catrip.gui;

/**
 *
 * @author  Sanjeev Agarwal
 */
public class MainFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        buildView();
    }
    
    
    private void buildView(){
        visualPanel.getVisualQueryDesignerPanel().setDnDGraphView(getListServicesPanel());
        repaint();
        
        //set main frame in all the panels..
        visualPanel.setMainFrame(this);
        commandPanel.setMainFrame(this);
        listServicesPanel.setMainFrame(this);
        outputPanel.setMainFrame(this);
        propertiesPanel.setMainFrame(this);
        
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        rootpanel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        listServicesPanel = new edu.duke.cabig.catrip.gui.ListServicesPanel();
        propertiesPanel = new edu.duke.cabig.catrip.gui.PropertiesPanel();
        rightPanel = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        commandPanel = new edu.duke.cabig.catrip.gui.CommandPanel();
        visualPanel = new edu.duke.cabig.catrip.gui.VisualPanel();
        outputPanel = new edu.duke.cabig.catrip.gui.OutputPanel();

        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        rootpanel.setPreferredSize(new java.awt.Dimension(1024, 768));
        jSplitPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(7);
        jSplitPane1.setFocusable(false);
        jSplitPane1.setOneTouchExpandable(true);
        jSplitPane2.setDividerLocation(550);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setLeftComponent(listServicesPanel);

        jSplitPane2.setRightComponent(propertiesPanel);

        org.jdesktop.layout.GroupLayout leftPanelLayout = new org.jdesktop.layout.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        jSplitPane1.setLeftComponent(leftPanel);

        jSplitPane3.setDividerLocation(500);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(commandPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .add(visualPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(466, Short.MAX_VALUE)
                .add(commandPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(jPanel1Layout.createSequentialGroup()
                .add(visualPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .add(34, 34, 34))
        );
        jSplitPane3.setTopComponent(jPanel1);

        jSplitPane3.setRightComponent(outputPanel);

        org.jdesktop.layout.GroupLayout rightPanelLayout = new org.jdesktop.layout.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        jSplitPane1.setRightComponent(rightPanel);

        org.jdesktop.layout.GroupLayout rootpanelLayout = new org.jdesktop.layout.GroupLayout(rootpanel);
        rootpanel.setLayout(rootpanelLayout);
        rootpanelLayout.setHorizontalGroup(
            rootpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(rootpanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                .addContainerGap())
        );
        rootpanelLayout.setVerticalGroup(
            rootpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(rootpanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                .addContainerGap())
        );
        getContentPane().add(rootpanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    public edu.duke.cabig.catrip.gui.CommandPanel getCommandPanel() {
        return commandPanel;
    }

    public edu.duke.cabig.catrip.gui.ListServicesPanel getListServicesPanel() {
        return listServicesPanel;
    }

    public edu.duke.cabig.catrip.gui.OutputPanel getOutputPanel() {
        return outputPanel;
    }

    public edu.duke.cabig.catrip.gui.PropertiesPanel getPropertiesPanel() {
        return propertiesPanel;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private edu.duke.cabig.catrip.gui.CommandPanel commandPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JPanel leftPanel;
    private edu.duke.cabig.catrip.gui.ListServicesPanel listServicesPanel;
    private edu.duke.cabig.catrip.gui.OutputPanel outputPanel;
    private edu.duke.cabig.catrip.gui.PropertiesPanel propertiesPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel rootpanel;
    private edu.duke.cabig.catrip.gui.VisualPanel visualPanel;
    // End of variables declaration//GEN-END:variables
    
    // List of components need to be linked.
    
    
    
    
    
}
