INSERT INTO SNP_PANEL ( SNP_PANEL_ID, SNP_PANEL_NAME, TECHNOLOGY, PANEL_DESCRIPTION, VENDOR,
VENDOR_PANEL_ID, VERSION, ASSAY_COUNT ) VALUES ( 
100, 'HumanHap300', 'Infinium II', 'Illumina HumanHap300 version 1 panel', 'Illumina'
, 'HumanHap300_(v1.1.0)', '1.1', NULL); 
commit;
 
