INSERT INTO STUDY_STDPOPUPLATION_ASSO ( STUDY_NAME, POPULATION_ID ) VALUES ( 
'CGEMS Prostate Cancer WGAS Phase 1A', 1); 
INSERT INTO STUDY_STDPOPUPLATION_ASSO ( STUDY_NAME, POPULATION_ID ) VALUES ( 
'CGEMS Prostate Cancer WGAS Phase 1A', 2); 
INSERT INTO STUDY_STDPOPUPLATION_ASSO ( STUDY_NAME, POPULATION_ID ) VALUES ( 
'CGEMS Prostate Cancer WGAS Phase 1A', 3); 
INSERT INTO STUDY_STDPOPUPLATION_ASSO ( STUDY_NAME, POPULATION_ID ) VALUES ( 
'CGEMS Prostate Cancer WGAS Phase 1A', 4); 
commit;
 
