INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU100', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU200', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU300', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU400', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU500', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU600', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU700', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU800', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU900', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU1000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU1100', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU1200', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU1300', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU1400', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU1500', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU1600', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU1700', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU1800', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU1900', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU2000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU2100', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU2200', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU2300', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU2400', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU2500', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU2600', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU2700', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU2800', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU2900', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU3000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU3100', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU3200', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU3300', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU3400', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU3500', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU3600', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU3700', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU3800', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU3900', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'DU4000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT4100', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT4200', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT4300', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT4400', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT4500', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT4600', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT4700', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT4800', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT4900', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT5000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT5100', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT5200', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT5300', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT5400', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT5500', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT5600', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT5700', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT5800', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT5900', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT6000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT6100', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT6200', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT6300', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT6400', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT6500', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT6600', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT6700', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT6800', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT6900', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT7000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT7100', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO STUDY_PARTICIPANT ( PARTICIPANT_DID, AGE_AT_DIAGNOSIS, AGE_AT_ENROLL, AGE_AT_DEATH,
DAYS_ON_STUDY, ETHNIC_GROUP_CODE, RACE_CODE, GENDER, SURVIVAL_STATUS, INSTITUTION_NAME, STUDY_NAME,
OFF_STUDY, DAYS_OFF_STUDY, POPULATION_ID, FAMILY_HISTORY, CASE_CONTROL_STATUS, AGE_AT_DIAGNOSIS_MIN,
AGE_AT_DIAGNOSIS_MAX, AGE_AT_ENROLL_MIN, AGE_AT_ENROLL_MAX, AGE_AT_DEATH_MIN,
AGE_AT_DEATH_MAX ) VALUES ( 
'TT7200', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
commit;
 
