package gov.nih.nci.cagrid.catissuecore.service.globus;

import gov.nih.nci.cagrid.catissuecore.service.CaTissueCoreImpl;

import java.rmi.RemoteException;

/** 
 *  DO NOT EDIT:  This class is autogenerated!
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class CaTissueCoreProviderImpl{
	
	CaTissueCoreImpl impl;
	
	public CaTissueCoreProviderImpl() throws RemoteException {
		impl = new CaTissueCoreImpl();
	}
	
	protected String getCallerIdentity() {
		String caller = org.globus.wsrf.security.SecurityManager.getManager().getCaller();
		if ((caller == null) || (caller.equals("<anonymous>"))) {
			return null;
		} else {
			return caller;
		}
	}
	

}
