
package edu.duke.cabig.catrip.gui.panels;


import edu.duke.cabig.catrip.gui.common.AttributeBean;
import edu.duke.cabig.catrip.gui.common.ClassBean;
import edu.duke.cabig.catrip.gui.components.CPanel;
import edu.duke.cabig.catrip.gui.config.GUIConfigurationLoader;
import edu.duke.cabig.catrip.gui.query.DCQLGenerator;
import edu.duke.cabig.catrip.gui.query.DCQLRegistry;
import edu.duke.cabig.catrip.gui.simplegui.CDEComboboxBean;
import edu.duke.cabig.catrip.gui.simplegui.SimpleGuiRegistry;
import gov.nih.nci.cagrid.cqlresultset.CQLQueryResults;
import gov.nih.nci.cagrid.data.utilities.CQLQueryResultsIterator;
import gov.nih.nci.catrip.dcql.DCQLQueryDocument;
import gov.nih.nci.catrip.fqe.engine.FederatedQueryEngine;
import gov.nih.nci.catrip.fqe.engine.FederatedQueryEngineImpl;
import java.io.File;
import java.io.FileInputStream;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 * Panel which contains the Execute button. More commands can be added here.
 *
 * @author  Sanjeev Agarwal
 */
public class CommandPanel extends CPanel {
    boolean simpleGui = true;
    
    
    /** Creates new form CommandPanel */
    public CommandPanel() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Netbeans Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        ExecuteCommand = new javax.swing.JButton();

        ExecuteCommand.setText("Execute Query");
        ExecuteCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecuteCommandActionPerformed(evt);
            }
        });

        add(ExecuteCommand);

    }// </editor-fold>//GEN-END:initComponents
    
    private void ExecuteCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecuteCommandActionPerformed
        
        if (simpleGui){
            executeSimpleGuiQuery();
        }else {
            executeVisualGuiQuery();
        }
        
    }//GEN-LAST:event_ExecuteCommandActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExecuteCommand;
    // End of variables declaration//GEN-END:variables
    
    private void executeSimpleGuiQuery(){
//        List cBeanList = SimpleGuiRegistry.getCurrentClassBeanList();
//        for (int i = 0; i < cBeanList.size(); i++) {
//            ClassBean cBean = (ClassBean)cBeanList.get(i);
//            System.out.println("XXXX-----XXXX  " + cBean.getFullyQualifiedName());
//            cBean.printAttributes();
//            System.out.println("XXXX-----XXXX");
//        }
//        System.out.println("====================== total classBean size:"+cBeanList.size());
        
        ArrayList<FilterRowPanel> list = SimpleGuiRegistry.getFilterList();
        for (int i = 0; i < list.size(); i++) {
            FilterRowPanel pnl = list.get(i);
            CDEComboboxBean cdeBean = (CDEComboboxBean)pnl.getCdeCombo().getSelectedItem();
            ClassBean cBean = cdeBean.getClassBean();
            SimpleGuiRegistry.addToBeanMap(cBean);
        }
        
        
        
        
//        HashMap beanMap = SimpleGuiRegistry.getBeanMap();
//        Iterator ii = beanMap.keySet().iterator();
//        while (ii.hasNext()){
//            String key = (String)ii.next();
//            ClassBean cBean = (ClassBean) beanMap.get(key);
//            System.out.println("XXXX-----XXXX  " + cBean.getFullyQualifiedName());
//            cBean.printAttributes();
//            System.out.println("XXXX-----XXXX");
//        }
        
        
        
        
//        for (int i = 0; i < list.size(); i++) {
//            FilterRowPanel pnl = list.get(i);
//            CDEComboboxBean cdeBean = (CDEComboboxBean)pnl.getCdeCombo().getSelectedItem();
//            ClassBean cBean = cdeBean.getClassBean();
//            System.out.println("XXXX-----XXXX  " + cBean.getFullyQualifiedName());
//            cBean.printAttributes();
//            System.out.println("XXXX-----XXXX");
//        }
        
        
        
        
        
    }
    
    private void executeVisualGuiQuery(){
        try {
            /** can dump the generated XML into a file also. */
//            FileWriter fop = new FileWriter(new File("dcql.xml"), false);
//            fop.write(DCQLGenerator.getDCQLText());
//            fop.close();
            
            FederatedQueryEngine fqe = new FederatedQueryEngineImpl();
            DCQLQueryDocument dcqlQueryDocument = DCQLGenerator.getDCQLDocument();
            
            // print the formatted DCQL on console or to a log file.
//            XmlOptions xmlOptions = new XmlOptions();
//            xmlOptions.setSavePrettyPrint();
//            xmlOptions.setSavePrettyPrintIndent(4);
//            xmlOptions.setUseDefaultNamespace();
//            System.out.println("\n\n ========= Executing this DCQL ================\n");
//            System.out.println(DCQLGenerator.getDCQLText(xmlOptions));
//            System.out.println("\n\n ==============================================\n\n\n\n\n");
            
            // clean the result table before you even try the new query...
            getMainFrame().getOutputPanel().cleanResults();
            
            CQLQueryResults results = fqe.execute(dcqlQueryDocument);
            
            if ( (results == null) || (results.getObjectResult() == null) || (results.getObjectResult().length == 0) ){
                JOptionPane.showMessageDialog(getMainFrame(), "No results found. Please check your query.");
            } else {
                
                // TODO - put the client config files of the individual service also in the caTRIP-config.xml or the services-mapping file some how.
                CQLQueryResultsIterator iterator = new CQLQueryResultsIterator(results, new FileInputStream(new File(GUIConfigurationLoader.getGUIConfiguration().getConfigRootLocation() + File.separator +"qe-client-config.wsdd")));
                
                ArrayList classBeanList = new ArrayList();
                
                ClassBean tmpObject = DCQLRegistry.getTargetNode().getAssociatedClassObject();
                
                while (iterator.hasNext()) {
                    Object obj = iterator.next();
                    ClassBean classBeanTmp = tmpObject.clone();
                    
                    ArrayList attributeList = classBeanTmp.getAttributes();
                    
                    for (int i = 0; i < attributeList.size(); i++) {
                        AttributeBean aBean = (AttributeBean) attributeList.get(i);
                        String attributeName = aBean.getAttributeName();
                        String methodName ="get"+attributeName.substring(0,1).toUpperCase() + attributeName.substring(1);
                        String value = "";
                        try{
                            Object attributeValue = ((Method)obj.getClass().getMethod(methodName)).invoke(obj);
                            if (attributeValue != null){
                                value = attributeValue.toString();
                            }
                        } catch (Exception eex) {
                            eex.printStackTrace();
                        }
                        aBean.setAttributeValue(value);
                    }
                    classBeanList.add(classBeanTmp);
                }
                
                getMainFrame().getOutputPanel().setResults(classBeanList);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    
}
