/*
 * CQLDesignerPanel.java
 *
 * Created on May 16, 2006, 3:18 PM
 */

package edu.duke.cabig.catrip.gui.panels;


import edu.duke.cabig.catrip.gui.components.CPanel;
import java.awt.Color;
import java.awt.Font;
import javax.swing.text.PlainDocument;
import org.bounce.text.xml.XMLEditorKit;
import org.bounce.text.xml.XMLStyleConstants;


/**
 *
 * @author  Sanjeev Agarwal
 */
public class CQLDesignerPanel extends CPanel {
    
    /** Creates new form CQLDesignerPanel */
    public CQLDesignerPanel() {
        initComponents();
        init();
    }
    
    private void init(){
        XMLEditorKit kit = new XMLEditorKit( true);
        kit.setWrapStyleWord( true);
        kit.setLineWrappingEnabled( true);
        getDcqlQueryEditorPane().getDocument().putProperty( PlainDocument.tabSizeAttribute, new Integer(4));
        kit.setStyle( XMLStyleConstants.ATTRIBUTE_NAME, new Color( 0,128,0), Font.PLAIN);
        kit.setStyle( XMLStyleConstants.ATTRIBUTE_VALUE, new Color( 128, 0, 255), Font.BOLD);
        kit.setStyle( XMLStyleConstants.ELEMENT_VALUE, new Color(0,0,0), Font.BOLD);
        kit.setStyle( XMLStyleConstants.ELEMENT_NAME, new Color(128, 0, 128), Font.PLAIN);
        getDcqlQueryEditorPane().setEditable(false);
        getDcqlQueryEditorPane().setEditorKit(kit);
    }
    
    public javax.swing.JEditorPane getDcqlQueryEditorPane() {
        return dcqlQueryEditorPane;
    }
    
    public void setDcqlQueryText(String cqlTxt) {
        getDcqlQueryEditorPane().setText(cqlTxt);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        dcqlQueryEditorPane = new javax.swing.JEditorPane();

        jScrollPane1.setViewportView(dcqlQueryEditorPane);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane dcqlQueryEditorPane;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
