

package edu.duke.cabig.catrip.gui.panels;

import edu.duke.cabig.catrip.gui.common.AttributeBean;
import edu.duke.cabig.catrip.gui.common.ClassBean;
import edu.duke.cabig.catrip.gui.simplegui.CDEComboboxBean;
import edu.duke.cabig.catrip.gui.simplegui.SimpleGuiRegistry;
import edu.duke.cabig.catrip.gui.simplegui.objectgraph.GraphObject;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Hashtable;
import java.util.List;
import javax.swing.JTextField;

/**
 *
 * @author  Sanjeev Agarwal
 */
public class FilterRowPanel extends javax.swing.JPanel {
    
    private CDEComboboxBean currentFilter = null;
    
    // for grouping similar Target objects... String key = cBean.getCDEName() + "_" +aBean.getCDEName()+"-"+cBean.getServiceName();
    private Hashtable uniqueFilterMap = new Hashtable();
    
    /** Creates new form FilterRowPanel */
    public FilterRowPanel() {
        initComponents();
        init();
    }
    
    private void init(){
        
        fillPredicateCombo();
        
//        fillCdeCombo1();
        
    }
    
    
    public JTextField getValueBox(){
        return valueTextBox;
    }
    
    public javax.swing.JComboBox getCdeCombo() {
        return cdeCombo;
    }
    
    public javax.swing.JComboBox getPredicateCombo() {
        return predicateCombo;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        cdeCombo = new javax.swing.JComboBox();
        cdeCombo = new edu.duke.cabig.catrip.gui.components.SteppedComboBox();
        valueTextBox = new javax.swing.JTextField();
        predicateCombo = new edu.duke.cabig.catrip.gui.components.SteppedComboBox();

        cdeCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cdeComboItemStateChanged(evt);
            }
        });

        valueTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valueTextBoxKeyReleased(evt);
            }
        });

        predicateCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                predicateComboItemStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(cdeCombo, 0, 379, Short.MAX_VALUE)
                .add(14, 14, 14)
                .add(predicateCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 142, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(14, 14, 14)
                .add(valueTextBox, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(valueTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(cdeCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(predicateCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(new java.awt.Component[] {cdeCombo, predicateCombo, valueTextBox}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents
    
    private void cdeComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cdeComboItemStateChanged
// clean filter from previous CDEComboboxBean and reset predicate and value fields..
        if (currentFilter != null){ // that means a filter was already set on this row...
            currentFilter.remove();
            getPredicateCombo().setSelectedIndex(0);
            getValueBox().setText("");
            
            SimpleGuiRegistry.getTargetGraphObject().getClassBean().removeAllUniqueAssociations();
//            HashMap allBeans = SimpleGuiRegistry.getCurrentClassBeanMap();//getBeanMap();
//            
//            Iterator itt = (allBeans.values()).iterator(); 
//            while(itt.hasNext()) {
//                ClassBean cBean = (ClassBean) itt.next();
//                cBean.removeAllUniqueAssociations();
//            }
//            SimpleGuiRegistry.setSimpleGuiChanged(true);
        }
        
    }//GEN-LAST:event_cdeComboItemStateChanged
    
    private void valueTextBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valueTextBoxKeyReleased
//        if (!valueTextBox.getText().trim().equalsIgnoreCase("")){
        CDEComboboxBean cdeBean = (CDEComboboxBean)getCdeCombo().getSelectedItem();
        cdeBean.getAttributeBean().setAttributeValue(valueTextBox.getText().trim());
        currentFilter = cdeBean;
//        }
    }//GEN-LAST:event_valueTextBoxKeyReleased
    
    private void predicateComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_predicateComboItemStateChanged
        
//        if (evt.getStateChange() == ItemEvent.SELECTED) {
//        } else
        
        if (evt.getStateChange() == ItemEvent.DESELECTED) {
            CDEComboboxBean cdeBean = (CDEComboboxBean)getCdeCombo().getSelectedItem();
            cdeBean.getAttributeBean().setPredicate(getPredicateCombo().getSelectedItem().toString());
        }
        
    }//GEN-LAST:event_predicateComboItemStateChanged
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cdeCombo;
    private edu.duke.cabig.catrip.gui.components.SteppedComboBox predicateCombo;
    private javax.swing.JTextField valueTextBox;
    // End of variables declaration//GEN-END:variables
    
    
    
    private void fillPredicateCombo(){
        getPredicateCombo().addItem("LIKE");
        getPredicateCombo().addItem("EQUAL_TO");
        getPredicateCombo().addItem("NOT_EQUAL_TO");
        getPredicateCombo().addItem("LESS_THAN");
        getPredicateCombo().addItem("LESS_THAN_EQUAL_TO");
        getPredicateCombo().addItem("GREATER_THAN");
        getPredicateCombo().addItem("GREATER_THAN_EQUAL_TO");
        getPredicateCombo().addItem("IS_NULL");
        getPredicateCombo().addItem("IS_NOT_NULL");
        
        getPredicateCombo().setSelectedIndex(0);
    }
    
    
    
    public void fillCdeCombo2(List<GraphObject> objs) {
        
        for (int i=0;i<objs.size();i++) {
            GraphObject gObj = objs.get(i);
            if (gObj.isDisplayable()){
                ClassBean cBean = gObj.getClassBean();
                ArrayList attributes = cBean.getAttributes();
                
                for (int j = 0; j < attributes.size(); j++) {
                    AttributeBean aBean = (AttributeBean)attributes.get(j);
                    CDEComboboxBean cdeBean = new CDEComboboxBean();
                    cdeBean.setGraphObject(gObj);
//                    cdeBean.setClassBean(cBean);
                    cdeBean.setAttributeBean(aBean);
                    getCdeCombo().addItem(cdeBean);
                }
            }
        }
        
        // add them in sorted order.. add all the filters in an array list than use collections to sort than add tham to combo.
//        Collections.sort(attributes); 
        
    }
    
    
    
    // not in use...
//    public void fillCdeCombo(List<ClassBean> objs) {
//        for (int i=0;i<objs.size();i++) {
//            ClassBean cBean = objs.get(i);
//            ArrayList attributes = cBean.getAttributes();
//            for (int j = 0; j < attributes.size(); j++) {
//                AttributeBean aBean = (AttributeBean)attributes.get(j);
//                CDEComboboxBean cdeBean = new CDEComboboxBean();
//                cdeBean.setClassBean(cBean);cdeBean.setAttributeBean(aBean);
//                getCdeCombo().addItem(cdeBean);
//            }
//        }
//    }
    
    
    // String key = cBean.getCDEName() + "_" +aBean.getCDEName()+"-"+cBean.getServiceName();
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
}




