/*
 * QueryEngineServiceSelectPanel.java
 *
 * Created on June 9, 2006, 1:36 PM
 */

package edu.duke.cabig.catrip.gui.panels;

import edu.duke.cabig.catrip.gui.components.CJFrame;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author  Sanjeev Agarwal
 */
public class QueryEngineServiceSelectPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form QueryEngineServiceSelectPanel
     */
    public QueryEngineServiceSelectPanel() {
        initComponents();
    }
    
    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Netbeans Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        searchEngineServiceListCombo = new javax.swing.JComboBox();
        lbl = new javax.swing.JLabel();
        setDefaultChkBox = new javax.swing.JCheckBox();
        selectBtn = new javax.swing.JButton();

        searchEngineServiceListCombo.setModel(getComboBoxModel());

        lbl.setText(java.util.ResourceBundle.getBundle("edu/duke/cabig/catrip/gui/resources/ResourceBundle").getString("QUERY_ENGINE_SERVICE_SELECT_PANEL_LBL1"));

        setDefaultChkBox.setText(java.util.ResourceBundle.getBundle("edu/duke/cabig/catrip/gui/resources/ResourceBundle").getString("QUERY_ENGINE_SERVICE_SELECT_PANEL_CHK_BOX"));
        setDefaultChkBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setDefaultChkBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        selectBtn.setText("Select");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lbl)
                    .add(layout.createSequentialGroup()
                        .add(setDefaultChkBox)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 377, Short.MAX_VALUE)
                        .add(selectBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(searchEngineServiceListCombo, 0, 546, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(lbl)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(searchEngineServiceListCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(setDefaultChkBox)
                    .add(selectBtn))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CJFrame cf = new CJFrame();cf.setTitle("Testing this panel");
                cf.getContentPane().add(new QueryEngineServiceSelectPanel());
                cf.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
                cf.setBounds(10,10,650,142);
                cf.setVisible(true);
            }
        });
    }
    
    private DefaultComboBoxModel getComboBoxModel(){
        DefaultComboBoxModel cb = new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2" });
        return cb;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl;
    private javax.swing.JComboBox searchEngineServiceListCombo;
    private javax.swing.JButton selectBtn;
    private javax.swing.JCheckBox setDefaultChkBox;
    // End of variables declaration//GEN-END:variables
    
}
