/*
 * ReturnedAttributesRowPanel.java
 *
 * Created on January 22, 2007, 10:45 AM
 */

package edu.duke.cabig.catrip.gui.panels;
import edu.duke.cabig.catrip.gui.common.ClassBean;
import edu.duke.cabig.catrip.gui.simplegui.CDEComboboxBean;
import edu.duke.cabig.catrip.gui.simplegui.SimpleGuiRegistry;
import org.apache.commons.logging.Log;
import edu.duke.cabig.catrip.gui.util.Logger;
import java.awt.event.ItemEvent;
import java.util.HashMap;
import java.util.Iterator;


/**
 *
 * @author  Sanjeev Agarwal
 */
public class ReturnedAttributesRowPanel extends javax.swing.JPanel {
    
    private ReturnedAttributesPanel containerPanel;
    
    // Define Logger..
    static Log log = Logger.getDefaultLogger();
    
    
    /** Creates new form ReturnedAttributesRowPanel */
    public ReturnedAttributesRowPanel() {
        initComponents();
    }
    
    public ReturnedAttributesRowPanel(ReturnedAttributesPanel parent_) {
        initComponents();
        this.containerPanel = parent_;
        getReturnedAttributeCombo().setRenderer(new CDEComboBoxRenderer());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        returnedAttributeCombo = new edu.duke.cabig.catrip.gui.components.SteppedComboBox();
        delFilterBtn = new javax.swing.JButton();

        returnedAttributeCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                returnedAttributeComboItemStateChanged(evt);
            }
        });

        delFilterBtn.setFont(new java.awt.Font("Tahoma", 1, 11));
        delFilterBtn.setForeground(new java.awt.Color(255, 0, 0));
        delFilterBtn.setText(org.openide.util.NbBundle.getMessage(ReturnedAttributesRowPanel.class, "ReturnedAttributesRowPanel.delFilterBtn.text")); // NOI18N
        delFilterBtn.setIconTextGap(0);
        delFilterBtn.setMargin(new java.awt.Insets(1, 1, 1, 1));
        delFilterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delFilterBtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(delFilterBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(returnedAttributeCombo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(delFilterBtn)
            .add(returnedAttributeCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void returnedAttributeComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_returnedAttributeComboItemStateChanged
        if (evt.getStateChange() == ItemEvent.DESELECTED) {
            log.info(" Returned Attribute Changed: "+getReturnedAttributeCombo().getSelectedItem());
        }
    }//GEN-LAST:event_returnedAttributeComboItemStateChanged
    
    private void delFilterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delFilterBtnActionPerformed
        // delete this entry from the parent's list..
        
        CDEComboboxBean cdeBean = (CDEComboboxBean)getReturnedAttributeCombo().getSelectedItem();
        String fullClassName = cdeBean.getClassBean().getFullyQualifiedName();
        String returndAttributeName = cdeBean.getAttributeBean().getAttributeName();
        String serviceName = cdeBean.getClassBean().getServiceName();
        
        // delete the returned attribute that is set in the SimpleGuiRegistry.
        SimpleGuiRegistry.getClassNameReturnedAttributeMap().remove(fullClassName);
        SimpleGuiRegistry.setNumReturnedAttribute(SimpleGuiRegistry.getNumReturnedAttribute() - 1);
        SimpleGuiRegistry.getReturnedAttributeForeignServices().remove(serviceName);
        
        // delete all phony filters as well, they will be added again after the new set of returnedAttributes are added.
        SimpleGuiRegistry.cleanPhonyFilterList();
        
        log.info(" Deleted Returned Attribute| Class: "+fullClassName + " | Attribute: "+ returndAttributeName+ " | Service: "+ serviceName);
        
        this.removeAll();
        containerPanel.removeRow(this);
    }//GEN-LAST:event_delFilterBtnActionPerformed
    
    public javax.swing.JComboBox getReturnedAttributeCombo(){
        return returnedAttributeCombo;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delFilterBtn;
    private edu.duke.cabig.catrip.gui.components.SteppedComboBox returnedAttributeCombo;
    // End of variables declaration//GEN-END:variables
    
}
