
package edu.duke.cabig.catrip.gui.panels;


import edu.duke.cabig.catrip.gui.common.ClassBean;
import edu.duke.cabig.catrip.gui.components.CPanel;
import org.netbeans.graph.api.GraphFactory;
import org.netbeans.graph.api.model.builtin.GraphDocument;
import edu.duke.cabig.catrip.gui.dnd.*;


import javax.swing.*;
import java.awt.datatransfer.*;
import java.awt.dnd.*;
import javax.swing.tree.*;



/**
 * The Panel which contains the Graph component.
 *
 * @author  Sanjeev Agarwal
 */
public class VisualQueryDesignerPanel extends CPanel {
    
    private int lastID = 0;
    private GraphDocument document;
    private JComponent view;
    private ListServicesPanel servicePanel;
    
    /** Creates new form VisualQueryDesignerPanel */
    public VisualQueryDesignerPanel() {
        initComponents();
        document = new GraphDocument();
    }
    
    public void showNodePrperties(ClassBean nodeName){
        getMainFrame().getPropertiesPanel().showNodeProperties(nodeName); 
    }
    
    public void setView(JComponent comp){
        add(comp);
        repaint();
    }
    
    public void linkCDEs(ClassNode source, ClassNode target){
        // here you can show first the dialog... then take the input and then set that..
        
        java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    LinkCDEPanel ws= new LinkCDEPanel();
                    ws.main(null);
                }
            });
    }
    
    public void showMsg(String msgStr){
        JOptionPane.showMessageDialog(getMainFrame(), msgStr);
    }
    public void showWarning(String msgStr){
        JOptionPane.showMessageDialog(getMainFrame(), msgStr, null ,JOptionPane.WARNING_MESSAGE);
    }
    
    public String createID(String prefix) {
        return prefix + ++ lastID;
    }
    public int getLastID(){
        return lastID;
    }
    public void resetID(){
        this.lastID = 0;
    }
    
    public JTree getTree() {
        return servicePanel.getTree();
    }
    
    /** Create a Graph document, DnD drag source and set into the Panel. */
    public void setDnDGraphView(ListServicesPanel sPanel){
        servicePanel = sPanel;
        
        DragGestureListener dgListener = new DragGestureListener() {
            public void dragGestureRecognized(DragGestureEvent dge) {
                //String info = (String) tree.getSelectionPath().getLastPathComponent().toString();
                DefaultMutableTreeNode infoLeaf = (DefaultMutableTreeNode) getTree().getSelectionPath().getLastPathComponent();
                
                if (!(  (getTree().getSelectionPath().getPathCount() <= 2)  ||  (getTree().getSelectionPath().getPathCount() == 4) )){
                    ClassBean classBean = (ClassBean) infoLeaf.getUserObject();  
                    String info = classBean.getId();//getDisplayName(); // names are complete package names.. so are defnintely different
                    //System.out.println("##### "+info);
                    Transferable transferable = new StringSelection(info);
                    dge.startDrag(null, transferable, null);
                }
            }
        };
        DragSource.getDefaultDragSource().createDefaultDragGestureRecognizer(getTree(), DnDConstants.ACTION_COPY_OR_MOVE, dgListener);
        
        view = GraphFactory.createView(document, new DocumentRenderer(), new ViewController(this), new EventHandler(this));
        
        add(new JScrollPane(view));
        
    }
    
    
    public GraphDocument getDocument() {
        return document;
    }
    
    
    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Netbeans Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(1, 0));

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    
    
    
    
//    public static void main(String[] args) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                JFrame jf = new JFrame("Testing this panel");
//                VisualQueryDesignerPanel vp = new VisualQueryDesignerPanel();
//                ListServicesPanel ls = new ListServicesPanel();
//                vp.setDnDGraphView(ls);
//
//                jf.setLayout(new java.awt.GridLayout());
//                jf.getContentPane().add(ls);
//                jf.getContentPane().add(vp);
//
//                jf.setBounds(10,10,400,200);
//                jf.setVisible(true);
//
//            }
//        });
//    }
    
    
    
    
}
