
CREATE TABLE CATRIP_QUERY
(
  ID            NUMBER(8)                       NOT NULL,
  FIRST_NAME    VARCHAR2(50 BYTE),
  LAST_NAME     VARCHAR2(100 BYTE),
  USER_NAME     VARCHAR2(25 BYTE),
  DESCRIPTION   VARCHAR2(255 BYTE),
  NAME          VARCHAR2(50 BYTE),
  DATE_CREATED  DATE,
  DATE_UPDATED  DATE,
  SOURCE        VARCHAR2(50 BYTE),
  VERSION       VARCHAR2(50 BYTE),
  INSTANCE      VARCHAR2(50 BYTE),
  DCQL          VARCHAR2(4000 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE DCQL_ATTRIBUTE
(
  ID               NUMBER(8)                    NOT NULL,
  CLASS_ID         INTEGER,
  NAME             VARCHAR2(2000 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE DCQL_CLASS
(
  ID               NUMBER(8)                    NOT NULL,
  CATRIP_QUERY_ID  INTEGER,
  NAME             VARCHAR2(2000 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;



