package gov.nih.nci.cagrid.caecae.service;

/** 
 *  DO NOT EDIT:  This class is autogenerated!
 * 
 *  @created by Introduce Toolkit version 1.0
 * 
 */
public class ServiceConfiguration {
	
	private String queryProcessorClass;
	
	private String appserviceUrl;
	

	
	public String getQueryProcessorClass() {
		return queryProcessorClass;
	}
	
	public void setQueryProcessorClass(String queryProcessorClass) {
		this.queryProcessorClass = queryProcessorClass;
	}

	
	public String getAppserviceUrl() {
		return appserviceUrl;
	}
	
	public void setAppserviceUrl(String appserviceUrl) {
		this.appserviceUrl = appserviceUrl;
	}

	
}
