--  ------------------------------------------- 
--  Generated by Enterprise Architect Ver. 4.01
--  Created On : Friday, 01 September, 2006 
--  DBMS       : Oracle 
--  ------------------------------------------- 

DROP TABLE DISEASE_EXTENT CASCADE CONSTRAINTS
;

CREATE TABLE DISEASE_EXTENT ( 
	ID NUMBER(8) NOT NULL,
	CLINICAL_MET_STAGE VARCHAR2(50),
	CLINICAL_NODE_STAGE VARCHAR2(50),
	CLINICAL_TUMOR_STAGE VARCHAR2(50),
	PATHOLOGIC_MET_STAGE VARCHAR2(50),    -- Tumor Registry : Dg_path_m  
	PATHOLOGIC_NODE_STAGE VARCHAR2(50),    -- Tumor Registry : Dg_path_n  
	PATHOLOGIC_TUMOR_STAGE VARCHAR2(50),    -- Tumor Registry : Dg_path_t  
	TNM_EDITION VARCHAR2(50),    -- Tumor Registry : Dg_TNM_Editn  
	TUMOR_SIZE FLOAT,    -- measurement is in centimeters 
	SEER_SUMMARY_STAGE VARCHAR2(50),
	PATHOLOGIC_AJCC_STAGE VARCHAR2(50),
	PATHOLOGIC_AJCC_STAGE_DESC VARCHAR2(100),
	CLINICAL_AJCC_STAGE VARCHAR2(50),
	CLINICAL_AJCC_STAGE_DESCRIPTOR VARCHAR2(100),
	REGIONAL_NODES_POSITIVE VARCHAR2(50),    -- Dg_Nd_Inv - Regional Nodes Positive  
	REGIONAL_NODES_EXAMINED VARCHAR2(50),    -- Dg_Nd_Exam - Regional Nodes Examined  
	BEST_AJCC_STAGE VARCHAR2(50),    -- Dg_Best_Stage Best AJCC stage, as calculated from derived Collaborative AJCC stage, or if no Collaborative stage, from Best of Path and Clin AJCC Stage.  
	BEST_SEER_SUMMARY_STAGE VARCHAR2(50),
	TUMOR_MARKER_1 VARCHAR2(50),
	TUMOR_MARKER_2 VARCHAR2(50),
	TUMOR_MARKER_3 VARCHAR2(50),
	DIAGNOSIS_ID NUMBER(8)
) 
;
COMMENT ON COLUMN DISEASE_EXTENT.PATHOLOGIC_MET_STAGE
    IS 'Tumor Registry : Dg_path_m '
;
COMMENT ON COLUMN DISEASE_EXTENT.PATHOLOGIC_NODE_STAGE
    IS 'Tumor Registry : Dg_path_n '
;
COMMENT ON COLUMN DISEASE_EXTENT.PATHOLOGIC_TUMOR_STAGE
    IS 'Tumor Registry : Dg_path_t '
;
COMMENT ON COLUMN DISEASE_EXTENT.TNM_EDITION
    IS 'Tumor Registry : Dg_TNM_Editn '
;
COMMENT ON COLUMN DISEASE_EXTENT.TUMOR_SIZE
    IS 'measurement is in centimeters'
;
COMMENT ON COLUMN DISEASE_EXTENT.REGIONAL_NODES_POSITIVE
    IS 'Dg_Nd_Inv - Regional Nodes Positive '
;
COMMENT ON COLUMN DISEASE_EXTENT.REGIONAL_NODES_EXAMINED
    IS 'Dg_Nd_Exam - Regional Nodes Examined '
;
COMMENT ON COLUMN DISEASE_EXTENT.BEST_AJCC_STAGE
    IS 'Dg_Best_Stage Best AJCC stage, as calculated from derived Collaborative AJCC stage, or if no Collaborative stage, from Best of Path and Clin AJCC Stage. '
;

ALTER TABLE DISEASE_EXTENT ADD CONSTRAINT PK_DiseaseExtent 
PRIMARY KEY (ID) 
;

ALTER TABLE DISEASE_EXTENT ADD CONSTRAINT FK_DISEASE_EXTENT_DIAGNOSIS 
FOREIGN KEY (DIAGNOSIS_ID) REFERENCES DIAGNOSIS (ID)
;























