/*L
  Copyright Duke Comprehensive Cancer Center

  Distributed under the OSI-approved BSD 3-Clause License.
  See http://ncip.github.com/catrip/LICENSE.txt for details.
L*/

INSERT INTO BREAST_SUR_PATHO_SPECIMANS ( ID, SURGICAL_PROCEDURE_MVR, OTHER_SURGICAL_PROCEDURE,
LYMPH_NODE_PROCEDURE, LATERALITY, LATERALITY_MVR ) VALUES ( 
55, 'NO MVR', 'left breast implant surgery', 'standard lymph node procedure', 'LATERALITY:right'
, 'NO MVR'); 
INSERT INTO BREAST_SUR_PATHO_SPECIMANS ( ID, SURGICAL_PROCEDURE_MVR, OTHER_SURGICAL_PROCEDURE,
LYMPH_NODE_PROCEDURE, LATERALITY, LATERALITY_MVR ) VALUES ( 
56, 'NO MVR', 'reconstructive surgeon in right breast', 'sentinel lymph node procedure'
, 'LATERALITY:left', 'NO MVR'); 
INSERT INTO BREAST_SUR_PATHO_SPECIMANS ( ID, SURGICAL_PROCEDURE_MVR, OTHER_SURGICAL_PROCEDURE,
LYMPH_NODE_PROCEDURE, LATERALITY, LATERALITY_MVR ) VALUES ( 
57, 'NO MVR', 'breast implant surgery', 'retroperitoneal lymph node procedure', 'LATERALITY:right'
, 'NO MVR'); 
INSERT INTO BREAST_SUR_PATHO_SPECIMANS ( ID, SURGICAL_PROCEDURE_MVR, OTHER_SURGICAL_PROCEDURE,
LYMPH_NODE_PROCEDURE, LATERALITY, LATERALITY_MVR ) VALUES ( 
58, 'NO MVR', 'bilateral implant surgery', 'axillary lymph node procedure', ' LATERALITY:right'
, 'NO MVR'); 
INSERT INTO BREAST_SUR_PATHO_SPECIMANS ( ID, SURGICAL_PROCEDURE_MVR, OTHER_SURGICAL_PROCEDURE,
LYMPH_NODE_PROCEDURE, LATERALITY, LATERALITY_MVR ) VALUES ( 
59, 'Not Available', 'N/A', 'sentinel lymph node procedure', 'LATERALITY:left', 'NO MVR'); 
INSERT INTO BREAST_SUR_PATHO_SPECIMANS ( ID, SURGICAL_PROCEDURE_MVR, OTHER_SURGICAL_PROCEDURE,
LYMPH_NODE_PROCEDURE, LATERALITY, LATERALITY_MVR ) VALUES ( 
60, 'NO MVR', 'postmastectomy reconstruction', 'sentinel lymph node procedure', 'LATERALITY:left'
, 'NO MVR'); 
INSERT INTO BREAST_SUR_PATHO_SPECIMANS ( ID, SURGICAL_PROCEDURE_MVR, OTHER_SURGICAL_PROCEDURE,
LYMPH_NODE_PROCEDURE, LATERALITY, LATERALITY_MVR ) VALUES ( 
61, 'NO MVR', 'right breast implant surgery', 'sentinel lymph node procedure', 'LATERALITY:right'
, 'NO MVR'); 
INSERT INTO BREAST_SUR_PATHO_SPECIMANS ( ID, SURGICAL_PROCEDURE_MVR, OTHER_SURGICAL_PROCEDURE,
LYMPH_NODE_PROCEDURE, LATERALITY, LATERALITY_MVR ) VALUES ( 
62, 'NO MVR', 'reconstructive surgeon', 'sentinel lymph node procedure', 'LATERALITY:both'
, 'NO MVR'); 
INSERT INTO BREAST_SUR_PATHO_SPECIMANS ( ID, SURGICAL_PROCEDURE_MVR, OTHER_SURGICAL_PROCEDURE,
LYMPH_NODE_PROCEDURE, LATERALITY, LATERALITY_MVR ) VALUES ( 
63, 'NO MVR', 'mastectomy surgery', 'retroperitoneal lymph node procedure', 'N/A', 'Not Available'); 
INSERT INTO BREAST_SUR_PATHO_SPECIMANS ( ID, SURGICAL_PROCEDURE_MVR, OTHER_SURGICAL_PROCEDURE,
LYMPH_NODE_PROCEDURE, LATERALITY, LATERALITY_MVR ) VALUES ( 
64, 'NO MVR', 'implant surgery', 'axillary lymph node procedure', ' LATERALITY:right'
, 'NO MVR'); 
INSERT INTO BREAST_SUR_PATHO_SPECIMANS ( ID, SURGICAL_PROCEDURE_MVR, OTHER_SURGICAL_PROCEDURE,
LYMPH_NODE_PROCEDURE, LATERALITY, LATERALITY_MVR ) VALUES ( 
65, 'NO MVR', 'postmastectomy reconstruction', 'sentinel lymph node procedure', 'LATERALITY:left'
, 'NO MVR'); 
COMMIT;
