/*L
  Copyright Duke Comprehensive Cancer Center

  Distributed under the OSI-approved BSD 3-Clause License.
  See http://ncip.github.com/catrip/LICENSE.txt for details.
L*/

delete from participant;
insert into participant (annotatable_entity_id,first_name,last_name) values (1,'Mickey','Mouse');
insert into participant (annotatable_entity_id,first_name,last_name) values (2,'Mary','Smith');
insert into participant (annotatable_entity_id,first_name,last_name) values (3,'','');
insert into participant (annotatable_entity_id,first_name,last_name) values (4,'Mouse','Mickey');
insert into participant (annotatable_entity_id,first_name,last_name) values (5,'re','t');
insert into participant (annotatable_entity_id,first_name,last_name) values (6,'Locke','May');
insert into participant (annotatable_entity_id,first_name,last_name) values (7,'','');
insert into participant (annotatable_entity_id,first_name,last_name) values (8,'May','Locke');
insert into participant (annotatable_entity_id,first_name,last_name) values (9,'May','Locke');
insert into participant (annotatable_entity_id,first_name,last_name) values (10,'May','Locke');
insert into participant (annotatable_entity_id,first_name,last_name) values (11,'Fruita','Fruitmick');
insert into participant (annotatable_entity_id,first_name,last_name) values (12,'ash','rai');
insert into participant (annotatable_entity_id,first_name,last_name) values (13,'Stewert','Martha');
insert into participant (annotatable_entity_id,first_name,last_name) values (14,'Sally','Smith');
insert into participant (annotatable_entity_id,first_name,last_name) values (15,'Demo','Demo');
insert into participant (annotatable_entity_id,first_name,last_name) values (16,'','');
insert into participant (annotatable_entity_id,first_name,last_name) values (17,'Joe','Public');
insert into participant (annotatable_entity_id,first_name,last_name) values (18,'John','Doe');
insert into participant (annotatable_entity_id,first_name,last_name) values (19,'','');
insert into participant (annotatable_entity_id,first_name,last_name) values (20,'Jack','Patient1');
insert into participant (annotatable_entity_id,first_name,last_name) values (21,'Bob','Patient2');
insert into participant (annotatable_entity_id,first_name,last_name) values (22,'Charlie','Patient3');
insert into participant (annotatable_entity_id,first_name,last_name) values (23,'David','Patient4');
insert into participant (annotatable_entity_id,first_name,last_name) values (24,'Ernie','Patient5');
insert into participant (annotatable_entity_id,first_name,last_name) values (25,'Frank','Patient6');
insert into participant (annotatable_entity_id,first_name,last_name) values (26,'','');
insert into participant (annotatable_entity_id,first_name,last_name) values (27,'','');
insert into participant (annotatable_entity_id,first_name,last_name) values (28,'Jack','Patient10');
insert into participant (annotatable_entity_id,first_name,last_name) values (29,'Bill','Patient11');
insert into participant (annotatable_entity_id,first_name,last_name) values (30,'James','Patient12');
insert into participant (annotatable_entity_id,first_name,last_name) values (31,'Charles','Patient13');
insert into participant (annotatable_entity_id,first_name,last_name) values (32,'Howard','Patient14');
insert into participant (annotatable_entity_id,first_name,last_name) values (33,'Peter','Patient15');
insert into participant (annotatable_entity_id,first_name,last_name) values (34,'Michael','Patient16');
insert into participant (annotatable_entity_id,first_name,last_name) values (35,'Rufus','Patient17');
insert into participant (annotatable_entity_id,first_name,last_name) values (36,'George','Patient18');
insert into participant (annotatable_entity_id,first_name,last_name) values (37,'Trevor','Patient19');
insert into participant (annotatable_entity_id,first_name,last_name) values (38,'Thomas','Patient20');
insert into participant (annotatable_entity_id,first_name,last_name) values (39,'Kyle','Patient21');
insert into participant (annotatable_entity_id,first_name,last_name) values (40,'Ronald','Patient22');
insert into participant (annotatable_entity_id,first_name,last_name) values (41,'Arnold','Pateint23');
insert into participant (annotatable_entity_id,first_name,last_name) values (42,'Brian','Patiemt24');
insert into participant (annotatable_entity_id,first_name,last_name) values (43,'Daniel','Patient25');
insert into participant (annotatable_entity_id,first_name,last_name) values (44,'Ernie','Patient26');
insert into participant (annotatable_entity_id,first_name,last_name) values (45,'Frank','Patient27');
insert into participant (annotatable_entity_id,first_name,last_name) values (46,'Gary','Patient28');
insert into participant (annotatable_entity_id,first_name,last_name) values (47,'Horace','Patient30');
insert into participant (annotatable_entity_id,first_name,last_name) values (48,'Jason','Patient31');
insert into participant (annotatable_entity_id,first_name,last_name) values (49,'Leonard','Patient32');
insert into participant (annotatable_entity_id,first_name,last_name) values (50,'Michael','Patient33');
insert into participant (annotatable_entity_id,first_name,last_name) values (51,'Nathan','Patient34');
insert into participant (annotatable_entity_id,first_name,last_name) values (52,'Oscar','Patient35');
insert into participant (annotatable_entity_id,first_name,last_name) values (53,'billy','jones');
insert into participant (annotatable_entity_id,first_name,last_name) values (54,'patient','dummy');
insert into participant (annotatable_entity_id,first_name,last_name) values (55,'Joe','Schmoe');
insert into participant (annotatable_entity_id,first_name,last_name) values (56,'bargain','plea');
insert into participant (annotatable_entity_id,first_name,last_name) values (57,'a','JKPart');
insert into participant (annotatable_entity_id,first_name,last_name) values (58,'','');
insert into participant (annotatable_entity_id,first_name,last_name) values (59,'koon','kaake');
insert into participant (annotatable_entity_id,first_name,last_name) values (60,'Patient','Cancer');
insert into participant (annotatable_entity_id,first_name,last_name) values (61,'','');
insert into participant (annotatable_entity_id,first_name,last_name) values (62,'','');
insert into participant (annotatable_entity_id,first_name,last_name) values (63,'t','t');
insert into participant (annotatable_entity_id,first_name,last_name) values (64,'Jane','Doe');
insert into participant (annotatable_entity_id,first_name,last_name) values (65,'','');
insert into participant (annotatable_entity_id,first_name,last_name) values (66,'','');
insert into participant (annotatable_entity_id,first_name,last_name) values (67,'','');
insert into participant (annotatable_entity_id,first_name,last_name) values (68,'','');
insert into participant (annotatable_entity_id,first_name,last_name) values (69,'','');
insert into participant (annotatable_entity_id,first_name,last_name) values (70,'','');
insert into participant (annotatable_entity_id,first_name,last_name) values (71,'Smith','Smith');
insert into participant (annotatable_entity_id,first_name,last_name) values (72,'Smithe','Smithe');
