/*L
  Copyright Duke Comprehensive Cancer Center

  Distributed under the OSI-approved BSD 3-Clause License.
  See http://ncip.github.com/catrip/LICENSE.txt for details.
L*/

INSERT INTO BREAST_OTHER_HISTOPATH_GRADES ( ID, SYSTEM_NAME, SCORE, SCORE_MVR,
MITOTIC_COUNT_O ) VALUES ( 
11, 'SBR', 1, 'NO MVR', 1); 
INSERT INTO BREAST_OTHER_HISTOPATH_GRADES ( ID, SYSTEM_NAME, SCORE, SCORE_MVR,
MITOTIC_COUNT ) VALUES ( 
12, 'Scarff Bloom Richardson sytem', 2, 'NO MVR', 8); 
INSERT INTO BREAST_OTHER_HISTOPATH_GRADES ( ID, SYSTEM_NAME, SCORE, SCORE_MVR,
MITOTIC_COUNT ) VALUES ( 
13, 'Elston and Ellis system', 1, 'NO MVR', 4); 
INSERT INTO BREAST_OTHER_HISTOPATH_GRADES ( ID, SYSTEM_NAME, SCORE, SCORE_MVR,
MITOTIC_COUNT ) VALUES ( 
14, 'SBR', 2, 'NO MVR', 11); 
INSERT INTO BREAST_OTHER_HISTOPATH_GRADES ( ID, SYSTEM_NAME, SCORE, SCORE_MVR,
MITOTIC_COUNT ) VALUES ( 
15, 'Scarff,Bloom,Richardson', 2, 'NO MVR', 9); 
INSERT INTO BREAST_OTHER_HISTOPATH_GRADES ( ID, SYSTEM_NAME, SCORE, SCORE_MVR,
MITOTIC_COUNT ) VALUES ( 
16, 'SBR system', 1, 'NO MVR', 3); 
INSERT INTO BREAST_OTHER_HISTOPATH_GRADES ( ID, SYSTEM_NAME, SCORE, SCORE_MVR,
MITOTIC_COUNT ) VALUES ( 
17, 'EE', 2, 'NO MVR', 14); 
INSERT INTO BREAST_OTHER_HISTOPATH_GRADES ( ID, SYSTEM_NAME, SCORE, SCORE_MVR,
MITOTIC_COUNT ) VALUES ( 
18, 'Scarff-Bloom-Richardson', 3, 'NO MVR', 20); 
INSERT INTO BREAST_OTHER_HISTOPATH_GRADES ( ID, SYSTEM_NAME, SCORE, SCORE_MVR,
MITOTIC_COUNT ) VALUES ( 
19, 'EE system', 1, 'NO MVR', 5); 
INSERT INTO BREAST_OTHER_HISTOPATH_GRADES ( ID, SYSTEM_NAME, SCORE, SCORE_MVR,
MITOTIC_COUNT ) VALUES ( 
20, 'Elston and Ellis', 1, 'NO MVR', 3); 

