/*L
  Copyright Duke Comprehensive Cancer Center

  Distributed under the OSI-approved BSD 3-Clause License.
  See http://ncip.github.com/catrip/LICENSE.txt for details.
L*/

INSERT INTO THREE_DIMENSIONAL_SIZES ( ID, GREATEST_DIMENSION, ADDITIONAL_DIMENSION_Y, ADDITIONAL_DIMENSION_Z, MVR ) VALUES ( 1, 3, 2, 2, 'NO MVR');
INSERT INTO THREE_DIMENSIONAL_SIZES ( ID, GREATEST_DIMENSION, ADDITIONAL_DIMENSION_Y, ADDITIONAL_DIMENSION_Z, MVR ) VALUES ( 2, 6, 5, 1, 'NO MVR');
INSERT INTO THREE_DIMENSIONAL_SIZES ( ID, GREATEST_DIMENSION, ADDITIONAL_DIMENSION_Y, ADDITIONAL_DIMENSION_Z, MVR ) VALUES ( 3, 5, 4, 2, 'NO MVR');
INSERT INTO THREE_DIMENSIONAL_SIZES ( ID, GREATEST_DIMENSION, ADDITIONAL_DIMENSION_Y, ADDITIONAL_DIMENSION_Z, MVR ) VALUES ( 4, 4, 2, 3, 'NO MVR');
INSERT INTO THREE_DIMENSIONAL_SIZES ( ID, GREATEST_DIMENSION, ADDITIONAL_DIMENSION_Y, ADDITIONAL_DIMENSION_Z, MVR ) VALUES ( 5, 5, 3, 5, 'NO MVR');
INSERT INTO THREE_DIMENSIONAL_SIZES ( ID, GREATEST_DIMENSION, ADDITIONAL_DIMENSION_Y, ADDITIONAL_DIMENSION_Z, MVR ) VALUES ( 6, 1, 1, 1, 'NO MVR');
INSERT INTO THREE_DIMENSIONAL_SIZES ( ID, GREATEST_DIMENSION, ADDITIONAL_DIMENSION_Y, ADDITIONAL_DIMENSION_Z, MVR ) VALUES ( 7, 6, 2, 5, 'NO MVR');
INSERT INTO THREE_DIMENSIONAL_SIZES ( ID, GREATEST_DIMENSION, ADDITIONAL_DIMENSION_Y, ADDITIONAL_DIMENSION_Z, MVR ) VALUES ( 8, 3, 1, 2, 'NO MVR');
INSERT INTO THREE_DIMENSIONAL_SIZES ( ID, GREATEST_DIMENSION, ADDITIONAL_DIMENSION_Y, ADDITIONAL_DIMENSION_Z, MVR ) VALUES ( 9, 5, 4, 2, 'NO MVR');
INSERT INTO THREE_DIMENSIONAL_SIZES ( ID, GREATEST_DIMENSION, ADDITIONAL_DIMENSION_Y, ADDITIONAL_DIMENSION_Z, MVR ) VALUES ( 10, 2, 1, 2, 'NOMVR'); 
COMMIT;
