spool cae_tables.log
set scan off;
@drop_tables.sql
@INVASIVE_BREAST_CARCINOMA.SQL
@BREAST_LOCATIONS.SQL
@BREAST_MICROCALCIFICATION_LOCATIONS.SQL

@ADDITIONAL_FINDINGS.SQL
@THREE_DIMENSIONAL_SIZES.SQL

@BREAST_SURGICAL_PATHOLOGY_SPECIMANS.SQL
@BREAST_SURGICAL_PROCEDURES.SQL

@BREAST_CANCER_TNMF_FINDINGS.SQL
@BREAST_METASTASIS_ANATOMIC_SITES.SQL

@BREAST_HISTOPATHOLOGIC_GRADES.SQL
@BREAST_NEOPLASM_HISTOPATHALOGIC_TYPES.SQL
@BREAST_SURGICAL_MARGINS.SQL

@ALTER_BACKBONE_TABLES.SQL

commit;

spool off
exit