delete from THREE_DIMENSIONAL_SIZES ;
delete from BREAST_OTHER_HISTOPATH_GRADES;
delete from BREAST_NOTT_HISTOPATH_GRADES;
delete from INVASIVE_BREAST_CARCINOMA;
delete from BREAST_SUR_PATHO_SPECIMANS;
delete from BREAST_SURGICAL_PROCEDURES;
delete from PARTICIPANT_IDENTIFIERS;
