
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
21, 3, 2, 2, 7, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
22, 3, 2, 1, 6, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
23, 2, 2, 2, 6, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
24, 2, 2, 1, 5, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
25, 3, 3, 2, 8, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
26, 2, 3, 2, 7, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
27, 3, 2, 2, 7, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
28, 3, 3, 3, 9, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
29, 2, 1, 1, 5, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
30, 3, 2, 2, 7, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
31, 3, 3, 2, 8, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
32, 3, 3, 1, 7, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
33, 3, 3, 2, 8, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
34, 3, 2, 2, 7, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
35, 3, 2, 1, 6, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
36, 2, 3, 1, 6, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
37, 3, 3, 2, 8, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
38, 2, 2, 1, 5, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
39, 3, 3, 2, 8, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
40, 2, 1, 1, 4, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
41, 2, 3, 2, 7, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
42, 3, 3, 2, 8, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
43, 3, 2, 1, 6, 'NO MVR'); 
INSERT INTO BREAST_NOTT_HISTOPATH_GRADES ( ID, TUBULE_FORMATION, NUCLEAR_PLEOMORPHISM,
MITOTIC_COUNT, TOTAL_SCORE, TOTAL_SCORE_MVR ) VALUES ( 
44, 3, 3, 3, 9, 'NO MVR'); 
COMMIT;
