insert into THREE_DIMENSIONAL_SIZES (ID,GREATEST_DIMENSION,ADDITIONAL_DIMENSION_Y,ADDITIONAL_DIMENSION_Z) values (1,11,6,13);
insert into THREE_DIMENSIONAL_SIZES (ID,GREATEST_DIMENSION,ADDITIONAL_DIMENSION_Y,ADDITIONAL_DIMENSION_Z) values (2,12,7,14);
insert into THREE_DIMENSIONAL_SIZES (ID,GREATEST_DIMENSION,ADDITIONAL_DIMENSION_Y,ADDITIONAL_DIMENSION_Z) values (3,13,8,15);
insert into THREE_DIMENSIONAL_SIZES (ID,GREATEST_DIMENSION,ADDITIONAL_DIMENSION_Y,ADDITIONAL_DIMENSION_Z) values (4,14,9,16);
insert into THREE_DIMENSIONAL_SIZES (ID,GREATEST_DIMENSION,ADDITIONAL_DIMENSION_Y,ADDITIONAL_DIMENSION_Z) values (5,15,10,17);
insert into THREE_DIMENSIONAL_SIZES (ID,GREATEST_DIMENSION,ADDITIONAL_DIMENSION_Y,ADDITIONAL_DIMENSION_Z) values (6,16,11,18);
insert into THREE_DIMENSIONAL_SIZES (ID,GREATEST_DIMENSION,ADDITIONAL_DIMENSION_Y,ADDITIONAL_DIMENSION_Z) values (7,17,12,19);
insert into THREE_DIMENSIONAL_SIZES (ID,GREATEST_DIMENSION,ADDITIONAL_DIMENSION_Y,ADDITIONAL_DIMENSION_Z) values (8,18,13,20);
insert into THREE_DIMENSIONAL_SIZES (ID,GREATEST_DIMENSION,ADDITIONAL_DIMENSION_Y,ADDITIONAL_DIMENSION_Z) values (9,19,14,21);
insert into THREE_DIMENSIONAL_SIZES (ID,GREATEST_DIMENSION,ADDITIONAL_DIMENSION_Y,ADDITIONAL_DIMENSION_Z) values (10,20,15,22);



--select 'insert into THREE_DIMENSIONAL_SIZES (ID,GREATEST_DIMENSION,ADDITIONAL_DIMENSION_Y,ADDITIONAL_DIMENSION_Z) values ('|| ID ||',' || to_char(ID+10) || ',' || to_char(ID+5) || ',' || to_char(ID+12) || ');' 
--from annotatable_entity where id <11