INSERT INTO BREAST_SURGICAL_PROCEDURES ( ID, SURGICAL_PROCEDURE ) VALUES ( 
55, 'axillary lymph node procedure'); 
INSERT INTO BREAST_SURGICAL_PROCEDURES ( ID, SURGICAL_PROCEDURE ) VALUES ( 
55, 'left breast implant surgery'); 
INSERT INTO BREAST_SURGICAL_PROCEDURES ( ID, SURGICAL_PROCEDURE ) VALUES ( 
56, 'sentinel lymph node procedure'); 
INSERT INTO BREAST_SURGICAL_PROCEDURES ( ID, SURGICAL_PROCEDURE ) VALUES ( 
56, 'reconstructive surgeon in right breast'); 
INSERT INTO BREAST_SURGICAL_PROCEDURES ( ID, SURGICAL_PROCEDURE ) VALUES ( 
57, 'breast implant surgery'); 
INSERT INTO BREAST_SURGICAL_PROCEDURES ( ID, SURGICAL_PROCEDURE ) VALUES ( 
57, 'bilateral implant surgery'); 
INSERT INTO BREAST_SURGICAL_PROCEDURES ( ID, SURGICAL_PROCEDURE ) VALUES ( 
58, 'standard lymph node procedure'); 

COMMIT;
