insert into BREAST_NOTT_HISTOPATH_GRADES (ID,TOTAL_SCORE,MITOTIC_COUNT) values (21,41,16);
insert into BREAST_NOTT_HISTOPATH_GRADES (ID,TOTAL_SCORE,MITOTIC_COUNT) values (22,42,17);
insert into BREAST_NOTT_HISTOPATH_GRADES (ID,TOTAL_SCORE,MITOTIC_COUNT) values (23,43,18);
insert into BREAST_NOTT_HISTOPATH_GRADES (ID,TOTAL_SCORE,MITOTIC_COUNT) values (24,44,19);
insert into BREAST_NOTT_HISTOPATH_GRADES (ID,TOTAL_SCORE,MITOTIC_COUNT) values (25,45,20);
insert into BREAST_NOTT_HISTOPATH_GRADES (ID,TOTAL_SCORE,MITOTIC_COUNT) values (26,46,21);
insert into BREAST_NOTT_HISTOPATH_GRADES (ID,TOTAL_SCORE,MITOTIC_COUNT) values (27,47,22);
insert into BREAST_NOTT_HISTOPATH_GRADES (ID,TOTAL_SCORE,MITOTIC_COUNT) values (28,48,23);
insert into BREAST_NOTT_HISTOPATH_GRADES (ID,TOTAL_SCORE,MITOTIC_COUNT) values (29,49,24);
insert into BREAST_NOTT_HISTOPATH_GRADES (ID,TOTAL_SCORE,MITOTIC_COUNT) values (30,50,25);


--select 'insert into BREAST_NOTT_HISTOPATH_GRADES (ID,TOTAL_SCORE,MITOTIC_COUNT) values ('|| ID ||',' || to_char(ID+20) || ',' || to_char(ID-5) || ');' 
--from annotatable_entity where id >20 and id<31 