insert into annotation_set values (1,1,'test');
insert into annotation_set values (2,1,'test');
insert into annotation_set values (3,1,'test');
insert into annotation_set values (4,1,'test');
insert into annotation_set values (5,1,'test');
insert into annotation_set values (6,1,'test');
insert into annotation_set values (7,1,'test');
insert into annotation_set values (8,1,'test');
insert into annotation_set values (9,1,'test');
insert into annotation_set values (10,1,'test');
insert into annotation_set values (11,1,'test');
insert into annotation_set values (12,1,'test');
insert into annotation_set values (13,1,'test');
insert into annotation_set values (14,1,'test');
insert into annotation_set values (15,1,'test');
insert into annotation_set values (16,1,'test');
insert into annotation_set values (17,1,'test');
insert into annotation_set values (18,1,'test');
insert into annotation_set values (19,1,'test');
insert into annotation_set values (20,1,'test');

commit;

