create user cae_test identified by cae_test
default tablespace users
temporary tablespace temp
quota unlimited on users;
grant connect to cae_test;

GRANT CREATE TABLE TO cae_test;
GRANT CREATE INDEXTYPE TO cae_test;
GRANT CREATE PROCEDURE TO cae_test;
GRANT CREATE SYNONYM TO cae_test;
GRANT CREATE TABLE TO cae_test;
GRANT CREATE TRIGGER TO cae_test;
GRANT CREATE TYPE TO cae_test;
GRANT CREATE VIEW TO cae_test;
GRANT CREATE SEQUENCE TO cae_test;
GRANT CREATE SESSION TO cae_test;

connect cae_test/cae_test;



CREATE TABLE ACCESSION
(
  ANNOTATABLE_ENTITY_ID      NUMBER(20)         NOT NULL,
  PARTICIPANT_ID             NUMBER(20),
  DISEASE_TYPE               VARCHAR2(50 BYTE),
  ACCESSION_DATE             DATE,
  SURGICAL_PATHOLOGY_NUMBER  VARCHAR2(200 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE ACCESSION_CHARACTERISTICS
(
  ID                        NUMBER(10,2),
  OTHER_SURGICAL_PROCEDURE  VARCHAR2(255 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE ADDITIONAL_FINDINGS
(
  ID              NUMBER(10,2)                  NOT NULL,
  OTHER_FINDINGS  VARCHAR2(255 BYTE),
  MVR             VARCHAR2(255 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE AEP
(
  EVENT_PARAMETERS_ID    NUMBER(20)             NOT NULL,
  SOURCE                 VARCHAR2(50 BYTE),
  SOURCE_DATE            DATE,
  ANNOTATABLE_ENTITY_ID  NUMBER(20),
  RID                    NUMBER(10)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE ANNOTATABLE_ENTITY
(
  ID  NUMBER(20)                                NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE ANNOTATIONS
(
  ANNOTATION_ID      NUMBER(20)                 NOT NULL,
  NAME               VARCHAR2(255 BYTE),
  TYPE               NUMBER(11),
  ANNOTATION_SET_ID  NUMBER(20)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE ANNOTATIONS_DATE_DATA
(
  VALUE          DATE,
  ANNOTATION_ID  NUMBER(20)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE ANNOTATIONS_DOUBLE_DATA
(
  VALUE          NUMBER(20,5),
  ANNOTATION_ID  NUMBER(20)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE ANNOTATIONS_LONG_DATA
(
  VALUE          VARCHAR2(4000 BYTE),
  ANNOTATION_ID  NUMBER(20)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE ANNOTATIONS_SET_RELATIONS
(
  ID             NUMBER(20)                     NOT NULL,
  CLASS_NAME     VARCHAR2(255 BYTE),
  PHI_PRESENT    VARCHAR2(10 BYTE),
  DISPLAY_TITLE  VARCHAR2(255 BYTE),
  DISPLAY_ORDER  NUMBER(11),
  LEVEL_CODE     VARCHAR2(50 BYTE),
  DISEASE_TYPE   VARCHAR2(50 BYTE),
  LEVEL_CODE_ID  NUMBER(20),
  MIN_OCCURS     VARCHAR2(10 BYTE),
  MAX_OCCURS     VARCHAR2(10 BYTE),
  EDITABLE       NUMBER(1)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE ANNOTATIONS_SET_RELATIONS_VIEW
(
  ID             NUMBER(20)                     NOT NULL,
  EDITABLE       NUMBER(1),
  CLASS_NAME     VARCHAR2(255 BYTE),
  PHI_PRESENT    VARCHAR2(10 BYTE),
  DISPLAY_TITLE  VARCHAR2(255 BYTE),
  DISPLAY_ORDER  NUMBER(11),
  DISEASE_TYPE   VARCHAR2(50 BYTE),
  MAX_OCCURS     VARCHAR2(10 BYTE),
  MIN_OCCURS     VARCHAR2(10 BYTE),
  LEVEL_ORDER    NUMBER(11),
  LEVEL_CODE     VARCHAR2(50 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE ANNOTATIONS_STRING_DATA
(
  VALUE          VARCHAR2(255 BYTE),
  ANNOTATION_ID  NUMBER(20)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE ANNOTATION_CODES
(
  CODE       VARCHAR2(10 BYTE)                  NOT NULL,
  CODE_TYPE  VARCHAR2(10 BYTE)                  NOT NULL,
  DESCRIP    VARCHAR2(100 BYTE)                 NOT NULL,
  ID         NUMBER(38)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE ANNOTATION_EVENT_PARAMETER
(
  EVENT_PARAMETERS_ID    NUMBER(20)             NOT NULL,
  SOURCE                 VARCHAR2(50 BYTE),
  SOURCE_DATE            DATE,
  ANNOTATABLE_ENTITY_ID  NUMBER(20),
  RID                    NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE ANNOTATION_SET
(
  ID                        NUMBER(20)          NOT NULL,
  ANNOTATION_EVENT_PARM_ID  NUMBER(20),
  TYPE                      VARCHAR2(255 BYTE),
  RID                       NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE ANNOTATION_VALUE
(
  ANNOTATION_VALUE_ID  NUMBER(20)               NOT NULL,
  ANNOTATION_ID        NUMBER(20),
  TYPE                 NUMBER(11),
  NAME                 VARCHAR2(255 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE AUDIT_LOG
(
  AUDIT_LOG_ID              NUMBER(20),
  USER_ID                   NUMBER(20),
  USER_NAME                 VARCHAR2(64 BYTE),
  USER_CURRENT_PRIVILEGE    VARCHAR2(512 BYTE),
  USER_CHANGE_TO_PRIVILEGE  VARCHAR2(512 BYTE),
  AUDIT_EVENT               VARCHAR2(32 BYTE),
  ENTITY_ID                 NUMBER(20),
  ENTITY_TYPE               VARCHAR2(64 BYTE),
  DISEASE_TYPE              VARCHAR2(64 BYTE),
  IMPORT_FILE_NAME          VARCHAR2(128 BYTE),
  SOURCE                    VARCHAR2(64 BYTE),
  HTTPSESSION_ID            VARCHAR2(64 BYTE),
  LOG_TIME                  VARCHAR2(28 BYTE),
  LOGGER                    VARCHAR2(256 BYTE),
  MESSAGE                   VARCHAR2(2000 BYTE),
  APP_NAME                  VARCHAR2(32 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE BREAST_CANCER_BIOMARKERS
(
  ID                     NUMBER(10,2),
  ESTROGEN_RECEPTOR      VARCHAR2(255 BYTE),
  PROGESTERONE_RECEPTOR  VARCHAR2(255 BYTE),
  HER2_STATUS            VARCHAR2(255 BYTE),
  HER2_TEST_TYPE         VARCHAR2(255 BYTE),
  EGFR_STATUS            VARCHAR2(252 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE BREAST_CANCER_TNMF_FINDINGS
(
  ID                       NUMBER(10,2)         NOT NULL,
  CATEGORY                 VARCHAR2(255 BYTE),
  PRIMARY_TUMOR_FINDING    VARCHAR2(255 BYTE),
  REGIONAL_NODES_FINDING   VARCHAR2(255 BYTE),
  DISTANT_MET_FINDING      VARCHAR2(255 BYTE),
  NUMBER_NODES_EXAMINED    INTEGER,
  NUMBER_NODES_INVOLVED    INTEGER,
  OTHER_MET_ANATOMIC_SITE  VARCHAR2(255 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE BREAST_LOCATIONS
(
  ID        NUMBER(10,2),
  LOCATION  VARCHAR2(255 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE BREAST_MC_LOCATIONS
(
  ID                           NUMBER(10,2),
  MICROCALCIFICATION_LOCATION  VARCHAR2(255 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE BREAST_MET_ANATOMIC_SITES
(
  ID                        NUMBER(10,2),
  METASTASIS_ANATOMIC_SITE  VARCHAR2(255 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE BREAST_NEO_HSTOPTHLGC_TYPES
(
  ID          NUMBER(10,2)                      NOT NULL,
  NAME        VARCHAR2(255 BYTE),
  NAME_MVR    VARCHAR2(255 BYTE),
  OTHER_NAME  VARCHAR2(255 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE BREAST_NOTT_HISTOPATH_GRADES
(
  ID                    NUMBER(10,2)            NOT NULL,
  TUBULE_FORMATION      INTEGER,
  NUCLEAR_PLEOMORPHISM  INTEGER,
  MITOTIC_COUNT_N       INTEGER,
  TOTAL_SCORE           INTEGER,
  TOTAL_SCORE_MVR       VARCHAR2(255 BYTE),
  MITOTIC_COUNT         INTEGER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE BREAST_OTHER_HISTOPATH_GRADES
(
  ID               NUMBER(10,2)                 NOT NULL,
  SYSTEM_NAME      VARCHAR2(255 BYTE),
  SCORE            INTEGER,
  SCORE_MVR        VARCHAR2(255 BYTE),
  MITOTIC_COUNT_O  INTEGER,
  MITOTIC_COUNT    INTEGER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE BREAST_SPECMN_CHARACTERSTIC
(
  ID                             NUMBER(10,2),
  LYMPH_NODE_SAMPLING_PROCEDURE  VARCHAR2(255 BYTE),
  LATERALITY                     VARCHAR2(255 BYTE),
  LATERALITY_MVR                 VARCHAR2(255 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE BREAST_SURGICAL_PROCEDURES
(
  ID                  NUMBER(10,2),
  SURGICAL_PROCEDURE  VARCHAR2(255 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE CAE_STAGED_XML
(
  ID               NUMBER(38)                   NOT NULL,
  IMPORTSESSIONID  VARCHAR2(50 BYTE),
  SOURCEID         NUMBER(38),
  FIRSTNAME        VARCHAR2(50 BYTE),
  LASTNAME         VARCHAR2(50 BYTE),
  ACCESSIONID      VARCHAR2(50 BYTE),
  ORGANID          NUMBER(38),
  IMPORTDATE       DATE,
  XMLRECORD        CLOB
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE CASE_LIST_ITEM
(
  ID              NUMBER(20)                    NOT NULL,
  PARTICIPANT_ID  NUMBER(20),
  USER_ID         NUMBER(20),
  DISEASE_TYPE    VARCHAR2(50 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE DATA_SOURCE
(
  ID        NUMBER(38)                          NOT NULL,
  NAME      VARCHAR2(50 BYTE),
  PRIORITY  NUMBER(11)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE DELETED_ANNOTATION_EVENT_PARAM
(
  ID                     NUMBER(20)             NOT NULL,
  SOURCE                 VARCHAR2(50 BYTE),
  SOURCE_DATE            DATE,
  ANNOTATABLE_ENTITY_ID  NUMBER(20),
  TIME_STAMP             DATE,
  DELETED_BY_USER        VARCHAR2(100 BYTE),
  DELETED_DATE           DATE
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE EVENT_PARAMETERS
(
  ID          NUMBER(20)                        NOT NULL,
  TIME_STAMP  DATE
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE INVASIVE_BREAST_CARCINOMA
(
  ID                         NUMBER(10,2)       NOT NULL,
  VENOUS_LYMPHATIC_INVASION  VARCHAR2(255 BYTE),
  LOCATION_MVR               VARCHAR2(255 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE LEVEL_CODE
(
  ID           NUMBER(20)                       NOT NULL,
  DESCRIPTION  VARCHAR2(50 BYTE),
  LEVEL_ORDER  NUMBER(11)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE MISSING_PARTS
(
  ID   NUMBER(20)                               NOT NULL,
  RID  NUMBER(10)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE PARTICIPANT
(
  ANNOTATABLE_ENTITY_ID  NUMBER(20)             NOT NULL,
  LAST_NAME              VARCHAR2(200 BYTE),
  FIRST_NAME             VARCHAR2(200 BYTE),
  BIRTH_DATE             DATE,
  PATIENT_IDENTIFIER     VARCHAR2(200 BYTE),
  GENDER                 VARCHAR2(200 BYTE),
  RACE                   VARCHAR2(200 BYTE),
  ETHNICITY              VARCHAR2(200 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE PARTICIPANT_IDENTIFIERS
(
  ID                     NUMBER(10,2),
  PARTICIPANT_ID         NUMBER(20)             NOT NULL,
  MEDICAL_RECORD_NUMBER  VARCHAR2(200 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE SPECIMEN
(
  ANNOTATABLE_ENTITY_ID  NUMBER(20)             NOT NULL,
  ACCESSION_ID           NUMBER(20),
  PARENT_SPECIMEN_ID     NUMBER(20),
  SURGICAL_LABEL         VARCHAR2(200 BYTE),
  IDENTIFIER             VARCHAR2(200 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE THREE_DIMENSIONAL_TUMOR_SIZE
(
  ID                      NUMBER(10,2)          NOT NULL,
  GREATEST_DIMENSION      INTEGER,
  ADDITIONAL_DIMENSION_Y  INTEGER,
  ADDITIONAL_DIMENSION_Z  INTEGER,
  MVR                     VARCHAR2(255 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX PK_ACCESSION_CHARACTERISTICS ON ACCESSION_CHARACTERISTICS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_BREAST_CANCER_BIOMARKERS ON BREAST_CANCER_BIOMARKERS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_BREAST_SPECMN_CHARACTERSTIC ON BREAST_SPECMN_CHARACTERSTIC
(ID)
LOGGING
NOPARALLEL;


ALTER TABLE ACCESSION_CHARACTERISTICS ADD (
  CONSTRAINT PK_ACCESSION_CHARACTERISTICS PRIMARY KEY (ID));


ALTER TABLE BREAST_CANCER_BIOMARKERS ADD (
  CONSTRAINT PK_BREAST_CANCER_BIOMARKERS PRIMARY KEY (ID));


ALTER TABLE BREAST_SPECMN_CHARACTERSTIC ADD (
  CONSTRAINT PK_BREAST_SPECMN_CHARACTERSTIC PRIMARY KEY (ID));


ALTER TABLE THREE_DIMENSIONAL_TUMOR_SIZE ADD (
  PRIMARY KEY (ID));



