/*
 * MainFrame.java
 *
 * Created on May 16, 2006, 2:23 PM
 */

package edu.duke.cabig.catrip.gui.wizard;


import edu.duke.cabig.catrip.gui.components.CJFrame;


/**
 *
 * @author  Sanjeev Agarwal
 */
public class MainFrame extends CJFrame {
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        buildView();
    }
    
    
    private void buildView(){
        visualPanel.getVisualQueryDesignerPanel().setDnDGraphView(getListServicesPanel());
        repaint();
        
        //set main frame in all the panels..
        visualPanel.setMainFrame(this);
        commandPanel.setMainFrame(this);
        listServicesPanel.setMainFrame(this);
        outputPanel.setMainFrame(this);
        propertiesPanel.setMainFrame(this);
        
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        rootpanel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        listServicesPanel = new edu.duke.cabig.catrip.gui.panels.ListServicesPanel();
        propertiesPanel = new edu.duke.cabig.catrip.gui.panels.PropertiesPanel();
        rightPanel = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        commandPanel = new edu.duke.cabig.catrip.gui.panels.CommandPanel();
        visualPanel = new edu.duke.cabig.catrip.gui.panels.VisualPanel();
        outputPanel = new edu.duke.cabig.catrip.gui.panels.OutputPanel();
        menuBar = new javax.swing.JMenuBar();
        servicesMenu = new javax.swing.JMenu();
        add = new javax.swing.JMenuItem();
        delete = new javax.swing.JMenuItem();
        queryMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        preferencesMenu = new javax.swing.JMenu();

        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("caTRIP Federated Query Builder");
        rootpanel.setPreferredSize(new java.awt.Dimension(1024, 768));
        jSplitPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(7);
        jSplitPane1.setFocusable(false);
        jSplitPane1.setOneTouchExpandable(true);
        jSplitPane2.setDividerLocation(550);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setLeftComponent(listServicesPanel);

        jSplitPane2.setRightComponent(propertiesPanel);

        org.jdesktop.layout.GroupLayout leftPanelLayout = new org.jdesktop.layout.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        jSplitPane1.setLeftComponent(leftPanel);

        jSplitPane3.setDividerLocation(500);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(commandPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .add(visualPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(466, Short.MAX_VALUE)
                .add(commandPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(jPanel1Layout.createSequentialGroup()
                .add(visualPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .add(34, 34, 34))
        );
        jSplitPane3.setTopComponent(jPanel1);

        jSplitPane3.setRightComponent(outputPanel);

        org.jdesktop.layout.GroupLayout rightPanelLayout = new org.jdesktop.layout.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        jSplitPane1.setRightComponent(rightPanel);

        org.jdesktop.layout.GroupLayout rootpanelLayout = new org.jdesktop.layout.GroupLayout(rootpanel);
        rootpanel.setLayout(rootpanelLayout);
        rootpanelLayout.setHorizontalGroup(
            rootpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(rootpanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                .addContainerGap())
        );
        rootpanelLayout.setVerticalGroup(
            rootpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(rootpanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                .addContainerGap())
        );
        getContentPane().add(rootpanel);

        servicesMenu.setText("Services");
        add.setText("Add Services");
        servicesMenu.add(add);

        delete.setText("Delete Services");
        servicesMenu.add(delete);

        menuBar.add(servicesMenu);

        queryMenu.setText("Query");
        jMenuItem1.setText("Retrieve Query");
        queryMenu.add(jMenuItem1);

        jMenuItem2.setText("Create Query");
        queryMenu.add(jMenuItem2);

        jMenuItem3.setText("Save Query");
        queryMenu.add(jMenuItem3);

        jMenuItem4.setText("Delete Query");
        queryMenu.add(jMenuItem4);

        jMenuItem5.setText("Execute Query");
        queryMenu.add(jMenuItem5);

        menuBar.add(queryMenu);

        preferencesMenu.setText("Preferences");
        menuBar.add(preferencesMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    public edu.duke.cabig.catrip.gui.panels.CommandPanel getCommandPanel() {
        return commandPanel;
    }

    public edu.duke.cabig.catrip.gui.panels.ListServicesPanel getListServicesPanel() {
        return listServicesPanel;
    }

    public edu.duke.cabig.catrip.gui.panels.OutputPanel getOutputPanel() {
        return outputPanel;
    }

    public edu.duke.cabig.catrip.gui.panels.PropertiesPanel getPropertiesPanel() {
        return propertiesPanel;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem add;
    private edu.duke.cabig.catrip.gui.panels.CommandPanel commandPanel;
    private javax.swing.JMenuItem delete;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JPanel leftPanel;
    private edu.duke.cabig.catrip.gui.panels.ListServicesPanel listServicesPanel;
    private javax.swing.JMenuBar menuBar;
    private edu.duke.cabig.catrip.gui.panels.OutputPanel outputPanel;
    private javax.swing.JMenu preferencesMenu;
    private edu.duke.cabig.catrip.gui.panels.PropertiesPanel propertiesPanel;
    private javax.swing.JMenu queryMenu;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel rootpanel;
    private javax.swing.JMenu servicesMenu;
    private edu.duke.cabig.catrip.gui.panels.VisualPanel visualPanel;
    // End of variables declaration//GEN-END:variables
    
    // List of components need to be linked.
    
    
    
    
    
}
