package gov.nih.nci.catrip.fqe.engine;



import gov.nih.nci.cagrid.cqlquery.LogicalOperator;
import gov.nih.nci.cagrid.cqlquery.Predicate;
import gov.nih.nci.cagrid.cqlresultset.CQLQueryResults;
import gov.nih.nci.cagrid.data.utilities.CQLQueryResultsIterator;

import gov.nih.nci.cagrid.dcql.Join;
import gov.nih.nci.cagrid.dcql.JoinCondition;
import gov.nih.nci.catrip.fqe.utils.PropertyReader;

import java.io.File;
import java.io.FileInputStream;

import java.lang.reflect.Method;

import java.util.ArrayList;
import java.util.List;


class ResultAggregator {
    
    private JoinCondition joinCondition;
   // private String rightJoinObject;
    
    ResultAggregator(JoinCondition joinCondition) {
        this.joinCondition = joinCondition;
        //this.rightJoinObject = rightJoinObject;        
    }
    /**
     * get the right join CDE and access the getter of CDE in right join object.     
     * bild the list of CDE values  
     * @param results
     * @return
     */
    List processResults(CQLQueryResults results){
        Join rightJoin = joinCondition.getRightJoin();
        
        String classNameStr = rightJoin.getObject();
        String cde = rightJoin.getProperty();
        //String cde = joinCondition.getRightJoinCDE();
        List resultList = new ArrayList(); 
        
         try {
             if (results != null) {
                 //CQLQueryResultsIterator iter = new CQLQueryResultsIterator(results, new FileInputStream(new File("src/gov/nih/nci/cagrid/client/client-config.wsdd")));
                 String clientConfigWsdd = PropertyReader.initProperties().getProperty("clientConfigWsdd");
                  CQLQueryResultsIterator iter = new CQLQueryResultsIterator(results, new FileInputStream(new File(clientConfigWsdd)));
                 Class className = Class.forName(classNameStr);
                 Method methodName = className.getMethod("get"+cde.substring(0,1).toUpperCase()+cde.substring(1,cde.length()));
                 while (iter.hasNext()) {
                       Object o = methodName.invoke(iter.next());
                       resultList.add(o.toString());
                 } 
             }
             
         } catch (Exception e ) {
             e.printStackTrace();
         }
       return resultList;
    }
    
    /**
     * Build group of Attributes based on the List generated by processResults method .
     * Attribute name would be left join CDE
     * Attribute value would be value from the list generated by processResults method
     * predicate is "EQUAL_TO"
     * Group with logical operator "OR"
     * @param list
     * @return
     */
    gov.nih.nci.cagrid.cqlquery.Group buildGroup(List list){
    
        gov.nih.nci.cagrid.cqlquery.Group cqlGroup = new gov.nih.nci.cagrid.cqlquery.Group();
        
        gov.nih.nci.cagrid.cqlquery.Attribute[] attrArray = new gov.nih.nci.cagrid.cqlquery.Attribute[list.size()];
        gov.nih.nci.cagrid.cqlquery.Attribute attr = null;
        String property = joinCondition.getLeftJoin().getProperty();
        //String property = joinCondition.getLeftJoinCDE();
        for(int i=0;i<list.size();i++) {
            attr = new gov.nih.nci.cagrid.cqlquery.Attribute();
            attr.setName(property);
            attr.setValue(list.get(i).toString());
            attr.setPredicate(gov.nih.nci.cagrid.cqlquery.Predicate.EQUAL_TO);
            attrArray[i]=attr;
        }
        
        // if the size of result set returned by sub query is zero , add IS_NULL 
        if (list.size() == 0) {
            attr = new gov.nih.nci.cagrid.cqlquery.Attribute();
            attr.setName(property);
            attr.setPredicate(Predicate.IS_NULL);
            attrArray = new gov.nih.nci.cagrid.cqlquery.Attribute[1];
            attrArray[0]=attr;
        }
        
        cqlGroup.setLogicRelation(LogicalOperator.fromString("OR"));
        cqlGroup.setAttribute(attrArray);
        
        return cqlGroup;
    }
/*    
    public static Group aggregateGroups(caBIG.cql.x1.govNihNciCagridCQLQuery.Group[] groupsTomerge){
        caBIG.cql.x1.govNihNciCagridCQLQuery.Group aggregatedGroup = caBIG.cql.x1.govNihNciCagridCQLQuery.Group.Factory.newInstance();
        List s = new ArrayList();
    
        for (int i=0;i<groupsTomerge.length;i++){
            caBIG.cql.x1.govNihNciCagridCQLQuery.Group cqlGroup1 = groupsTomerge[i];
            Attribute[] attrArray = cqlGroup1.getAttributeArray();
            
            for (int j=0;j<attrArray.length;j++) {
                Attribute a = (Attribute)attrArray[i];
                s.add(a);
            }

        }
        
        
        Attribute[] attrArray1 = new Attribute[s.size()];
        System.out.println(s.size());
        Iterator sitr = s.iterator();
        int c=0;
        while (sitr.hasNext()) {
            Attribute a  = (Attribute)sitr.next();
            attrArray1[c] = a;
            System.out.println(c);
            c++;
        }
        System.out.println(attrArray1.length);
        aggregatedGroup.setLogicRelation(LogicalOperator.OR);
        aggregatedGroup.addNewAttribute();
        aggregatedGroup.setAttributeArray(attrArray1);
        return aggregatedGroup;
    }
*/
}
