package gov.nih.nci.cagrid.cgems.service.globus;

import gov.nih.nci.cagrid.cgems.service.CGEMSImpl;

import java.rmi.RemoteException;

/** 
 *  DO NOT EDIT:  This class is autogenerated!
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class CGEMSProviderImpl{
	
	CGEMSImpl impl;
	
	public CGEMSProviderImpl() throws RemoteException {
		impl = new CGEMSImpl();
	}
	
	protected String getCallerIdentity() {
		String caller = org.globus.wsrf.security.SecurityManager.getManager().getCaller();
		if ((caller == null) || (caller.equals("<anonymous>"))) {
			return null;
		} else {
			return caller;
		}
	}
	

}
