/*L
  Copyright Duke Comprehensive Cancer Center

  Distributed under the OSI-approved BSD 3-Clause License.
  See http://ncip.github.com/catrip/LICENSE.txt for details.
L*/

create user tumor_registry identified by tumor_registry
default tablespace users
temporary tablespace temp
quota unlimited on users;
grant connect to tumor_registry;

GRANT CREATE TABLE TO tumor_registry;
GRANT CREATE INDEXTYPE TO tumor_registry;
GRANT CREATE PROCEDURE TO tumor_registry;
GRANT CREATE SYNONYM TO tumor_registry;
GRANT CREATE TABLE TO tumor_registry;
GRANT CREATE TRIGGER TO tumor_registry;
GRANT CREATE TYPE TO tumor_registry;
GRANT CREATE VIEW TO tumor_registry;
GRANT CREATE SEQUENCE TO tumor_registry;
GRANT CREATE SESSION TO tumor_registry;

connect tumor_registry/tumor_registry;



CREATE TABLE ADDRESS
(
  ID         NUMBER(8)                          NOT NULL,
  ADDRESS_1  VARCHAR2(255 BYTE),
  ADDRESS_2  VARCHAR2(255 BYTE),
  ZIPCODE    VARCHAR2(20 BYTE),
  CITY       VARCHAR2(100 BYTE),
  STATE      VARCHAR2(50 BYTE),
  COUNTY     VARCHAR2(50 BYTE),
  COUNTRY    VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PATIENT
(
  ID            NUMBER(8)                       NOT NULL,
  FIRST_NAME    VARCHAR2(50 BYTE),
  MIDDLE_NAME   VARCHAR2(50 BYTE),
  LAST_NAME     VARCHAR2(100 BYTE),
  SUFFIX        VARCHAR2(50 BYTE),
  BIRTH_DATE    DATE,
  DEATH_DATE    DATE,
  RACE          VARCHAR2(50 BYTE),
  SEX           VARCHAR2(50 BYTE),
  ETHNIC_GROUP  VARCHAR2(50 BYTE),
  AUTOPSY       VARCHAR2(200 BYTE),
  ADDRESS_ID    NUMBER(8)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE DIAGNOSIS
(
  ID                      NUMBER(8)             NOT NULL,
  FIRST_CONTACT_DATE      DATE,
  INITIAL_DIAGNOSIS_DATE  DATE,
  AGE_AT_DIAGNOSIS        NUMBER(8),
  CAUSE_OF_DEATH          VARCHAR2(100 BYTE),
  BEHAVIOR                VARCHAR2(100 BYTE),
  HISTOLOGY               VARCHAR2(100 BYTE),
  HISTOLOGY_CODE          NUMBER(8),
  HISTOLOGIC_GRADE        VARCHAR2(100 BYTE),
  LATERALITY              VARCHAR2(100 BYTE),
  PRIMARY_SITE            VARCHAR2(100 BYTE),
  PRIMARY_SITE_CODE       VARCHAR2(100 BYTE),
  CLASS_OF_CASE           VARCHAR2(100 BYTE),
  CLASS_OF_CASE_CODE      NUMBER(8,2),
  PATIENT_ID              NUMBER(8),
  ADDRESS_ID              NUMBER(8)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE DISEASE_EXTENT
(
  ID                              NUMBER(8)     NOT NULL,
  CLINICAL_MET_STAGE              VARCHAR2(50 BYTE),
  CLINICAL_NODE_STAGE             VARCHAR2(50 BYTE),
  CLINICAL_TUMOR_STAGE            VARCHAR2(50 BYTE),
  PATHOLOGIC_MET_STAGE            VARCHAR2(50 BYTE),
  PATHOLOGIC_NODE_STAGE           VARCHAR2(50 BYTE),
  PATHOLOGIC_TUMOR_STAGE          VARCHAR2(50 BYTE),
  TNM_EDITION                     VARCHAR2(50 BYTE),
  TUMOR_SIZE                      FLOAT(126),
  PATHOLOGIC_AJCC_STAGE           VARCHAR2(50 BYTE),
  PATHOLOGIC_AJCC_STAGE_DESC      VARCHAR2(100 BYTE),
  CLINICAL_AJCC_STAGE             VARCHAR2(50 BYTE),
  CLINICAL_AJCC_STAGE_DESCRIPTOR  VARCHAR2(100 BYTE),
  REGIONAL_NODES_POSITIVE         NUMBER(8),
  REGIONAL_NODES_EXAMINED         NUMBER(8),
  BEST_AJCC_STAGE                 VARCHAR2(50 BYTE),
  BEST_SEER_SUMMARY_STAGE         VARCHAR2(50 BYTE),
  TUMOR_MARKER_1                  VARCHAR2(50 BYTE),
  TUMOR_MARKER_2                  VARCHAR2(50 BYTE),
  TUMOR_MARKER_3                  VARCHAR2(50 BYTE),
  DIAGNOSIS_ID                    NUMBER(8),
  REG_NODES_EXAMINED_QUALIFIER    VARCHAR2(50 BYTE),
  REG_NODES_POSITIVE_QUALIFIER    VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ACTIVITY_SUMMARY
(
  ID                        NUMBER(8)           NOT NULL,
  LOCAL_DATE                DATE,
  SUMMARY_DATE              DATE,
  LOCAL_CHARACTERIZATION    VARCHAR2(100 BYTE),
  SUMMARY_CHARACTERIZATION  VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COLLABORATIVE_STAGING
(
  ID                         NUMBER(8)          NOT NULL,
  EXTENSION                  VARCHAR2(50 BYTE),
  TUMOR_SIZE                 VARCHAR2(50 BYTE),
  TUMOR_SIZE_EXT_EVALUATION  VARCHAR2(50 BYTE),
  LYMPH_NODES                VARCHAR2(50 BYTE),
  LYMPH_NODES_AT_EVALUATION  VARCHAR2(50 BYTE),
  MET_EVALUATION             VARCHAR2(50 BYTE),
  MET_AT_DIAGNOSIS           VARCHAR2(50 BYTE),
  DERIVED_TUMOR_STAGE        VARCHAR2(50 BYTE),
  DERIVED_TUMOR_DESCRIPTOR   VARCHAR2(255 BYTE),
  DERIVED_NODE_STAGE         VARCHAR2(50 BYTE),
  DERIVED_NODE_DESCRIPTOR    VARCHAR2(255 BYTE),
  DERIVED_MET_STAGE          VARCHAR2(50 BYTE),
  DERIVED_MET_DESCRIPTOR     VARCHAR2(255 BYTE),
  DERIVED_AJCC_STAGE         VARCHAR2(50 BYTE),
  DERIVED_SEER_SUMMARY_1977  VARCHAR2(50 BYTE),
  DERIVED_SEER_SUMMARY_2000  VARCHAR2(50 BYTE),
  SITE_SPECIFIC_FACTOR_1     VARCHAR2(50 BYTE),
  SITE_SPECIFIC_FACTOR_2     VARCHAR2(50 BYTE),
  SITE_SPECIFIC_FACTOR_3     VARCHAR2(50 BYTE),
  SITE_SPECIFIC_FACTOR_4     VARCHAR2(50 BYTE),
  SITE_SPECIFIC_FACTOR_5     VARCHAR2(50 BYTE),
  SITE_SPECIFIC_FACTOR_6     VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE DISTANT_SITE
(
  ID                 NUMBER(8)                  NOT NULL,
  NAME               VARCHAR2(50 BYTE),
  RECURRENCE_ID      NUMBER(8),
  DISEASE_EXTENT_ID  NUMBER(8)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE FIRST_COURSE_TRMT_SUMMARY
(
  ID                             NUMBER(8)      NOT NULL,
  FIRST_SURGERY_DATE             DATE,
  MOST_DEFINITIVE_SURGERY_DATE   DATE,
  FIRST_TREATMENT_DATE           DATE,
  FIRST_SYSTEMIC_TREATMENT_DATE  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE FOLLOW_UP
(
  ID              NUMBER(8)                     NOT NULL,
  CANCER_STATUS   VARCHAR2(100 BYTE),
  CONTACT_METHOD  VARCHAR2(100 BYTE),
  CONTACT_DATE    DATE,
  DIAGNOSIS_ID    NUMBER(8)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PATIENT_IDENTIFIER
(
  ID                     NUMBER(8)              NOT NULL,
  MEDICAL_RECORD_NUMBER  VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE RECURRENCE
(
  ID               NUMBER(8)                    NOT NULL,
  RECURRENCE_DATE  DATE,
  TYPE             VARCHAR2(255 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ACTIVITY
(
  ID                    NUMBER(8)               NOT NULL,
  COURSE                NUMBER(8),
  STOP_DATE             DATE,
  AT_LOCAL_FACILITY     NUMBER(8),
  NUMBER_OF_TREATMENTS  VARCHAR2(50 BYTE),
  LOCATION              VARCHAR2(100 BYTE),
  START_DATE            DATE,
  CHARACTERIZATION      VARCHAR2(255 BYTE),
  VOLUME                VARCHAR2(100 BYTE),
  REGIONAL_DOSE         VARCHAR2(100 BYTE),
  BOOST_DOSE            VARCHAR2(100 BYTE),
  BOOST_MODALITY        VARCHAR2(100 BYTE),
  REGIONAL_MODALITY     VARCHAR2(100 BYTE),
  DISCRIMINATOR         VARCHAR2(50 BYTE),
  DIAGNOSIS_ID          NUMBER(8),
  PERFORMED_INDICATOR   VARCHAR2(10 BYTE),
  SUMMARY_ACTIVITY_ID   NUMBER(8),
  LOCAL_ACTIVITY_ID     NUMBER(8),
  TREATMENT_TYPE        VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PATIENT_IDENTIFIER_BACKUP
(
  ID                     NUMBER(8)              NOT NULL,
  MEDICAL_RECORD_NUMBER  VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PK_ACTIVITY ON ACTIVITY
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_ACTIVITY_SUMMARY ON ACTIVITY_SUMMARY
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_ADDRESS ON ADDRESS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_COLLABORATIVE_STAGING ON COLLABORATIVE_STAGING
(ID)
LOGGING
NOPARALLEL;


CREATE INDEX HISTO_IND ON DIAGNOSIS
(LOWER("HISTOLOGY"))
LOGGING
NOPARALLEL;


CREATE INDEX HISTO_GRADE_IND ON DIAGNOSIS
(LOWER("HISTOLOGIC_GRADE"))
LOGGING
NOPARALLEL;


CREATE INDEX PRIMARY_SITE_IND ON DIAGNOSIS
(LOWER("PRIMARY_SITE"))
LOGGING
NOPARALLEL;


CREATE INDEX CAUSE_OF_DEATH_IND ON DIAGNOSIS
(LOWER("CAUSE_OF_DEATH"))
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_DIAGNOSIS ON DIAGNOSIS
(ID)
LOGGING
NOPARALLEL;


CREATE INDEX CLIN_NODE_STAGE_IND ON DISEASE_EXTENT
(LOWER("CLINICAL_NODE_STAGE"))
LOGGING
NOPARALLEL;


CREATE INDEX TUMOR_SIZE_IND ON DISEASE_EXTENT
(TUMOR_SIZE)
LOGGING
NOPARALLEL;


CREATE INDEX CLIN_MET_STAGE_IND ON DISEASE_EXTENT
(LOWER("CLINICAL_MET_STAGE"))
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_DISEASEEXTENT ON DISEASE_EXTENT
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_DISTANT_SITE ON DISTANT_SITE
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_FIRST_COURSE_TRMT_SUMMARY ON FIRST_COURSE_TRMT_SUMMARY
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_FOLLOW_UP ON FOLLOW_UP
(ID)
LOGGING
NOPARALLEL;


CREATE INDEX SUFFIX_IND ON PATIENT
(LOWER("SUFFIX"))
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_PARTICIPANT ON PATIENT
(ID)
LOGGING
NOPARALLEL;


CREATE INDEX RACE_IND ON PATIENT
(LOWER("RACE"))
LOGGING
NOPARALLEL;


CREATE INDEX DATE_OF_BIRTH_IND ON PATIENT
(BIRTH_DATE)
LOGGING
NOPARALLEL;


CREATE INDEX MRN_IND ON PATIENT_IDENTIFIER
(LOWER("MEDICAL_RECORD_NUMBER"))
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_PATIENT_IDENTIFIER ON PATIENT_IDENTIFIER
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_RECURRENCE ON RECURRENCE
(ID)
LOGGING
NOPARALLEL;


ALTER TABLE ADDRESS ADD (
  CONSTRAINT PK_ADDRESS PRIMARY KEY (ID));


ALTER TABLE PATIENT ADD (
  CONSTRAINT PK_PARTICIPANT PRIMARY KEY (ID));


ALTER TABLE DIAGNOSIS ADD (
  CONSTRAINT PK_DIAGNOSIS PRIMARY KEY (ID));


ALTER TABLE DISEASE_EXTENT ADD (
  CONSTRAINT PK_DISEASEEXTENT PRIMARY KEY (ID));


ALTER TABLE ACTIVITY_SUMMARY ADD (
  CONSTRAINT PK_ACTIVITY_SUMMARY PRIMARY KEY (ID));


ALTER TABLE COLLABORATIVE_STAGING ADD (
  CONSTRAINT PK_COLLABORATIVE_STAGING PRIMARY KEY (ID));


ALTER TABLE DISTANT_SITE ADD (
  CONSTRAINT PK_DISTANT_SITE PRIMARY KEY (ID));


ALTER TABLE FIRST_COURSE_TRMT_SUMMARY ADD (
  CONSTRAINT PK_FIRST_COURSE_TRMT_SUMMARY PRIMARY KEY (ID));


ALTER TABLE FOLLOW_UP ADD (
  CONSTRAINT PK_FOLLOW_UP PRIMARY KEY (ID));


ALTER TABLE PATIENT_IDENTIFIER ADD (
  CONSTRAINT PK_PATIENT_IDENTIFIER PRIMARY KEY (ID));


ALTER TABLE RECURRENCE ADD (
  CONSTRAINT PK_RECURRENCE PRIMARY KEY (ID));


ALTER TABLE ACTIVITY ADD (
  CONSTRAINT PK_ACTIVITY PRIMARY KEY (ID));


ALTER TABLE PATIENT ADD (
  CONSTRAINT FK_PATIENT_ADDRESS FOREIGN KEY (ADDRESS_ID) 
    REFERENCES ADDRESS (ID));


ALTER TABLE DIAGNOSIS ADD (
  CONSTRAINT FK_DIAGNOSIS_PATIENT FOREIGN KEY (PATIENT_ID) 
    REFERENCES PATIENT (ID));

ALTER TABLE DIAGNOSIS ADD (
  CONSTRAINT FK_DIAGNOSIS_ADDRESS FOREIGN KEY (ADDRESS_ID) 
    REFERENCES ADDRESS (ID));


ALTER TABLE COLLABORATIVE_STAGING ADD (
  CONSTRAINT FK_COLLABORATIVE_STA_DIAGNOSIS FOREIGN KEY (ID) 
    REFERENCES DIAGNOSIS (ID) DISABLE);


ALTER TABLE DISTANT_SITE ADD (
  CONSTRAINT FK_DISTANT_SITE_DISEASE_EXTENT FOREIGN KEY (DISEASE_EXTENT_ID) 
    REFERENCES DISEASE_EXTENT (ID));


ALTER TABLE FIRST_COURSE_TRMT_SUMMARY ADD (
  CONSTRAINT FK_FIRST_COURSE_TRMT_DIAGNOSIS FOREIGN KEY (ID) 
    REFERENCES DIAGNOSIS (ID));


ALTER TABLE FOLLOW_UP ADD (
  CONSTRAINT FK_FOLLOW_UP_DIAGNOSIS FOREIGN KEY (DIAGNOSIS_ID) 
    REFERENCES DIAGNOSIS (ID));


ALTER TABLE ACTIVITY ADD (
  CONSTRAINT FK_ACTIVITY_DIAGNOSIS FOREIGN KEY (DIAGNOSIS_ID) 
    REFERENCES DIAGNOSIS (ID));



