/*L
  Copyright Duke Comprehensive Cancer Center

  Distributed under the OSI-approved BSD 3-Clause License.
  See http://ncip.github.com/catrip/LICENSE.txt for details.
L*/

spool cgems_tables.log
set scan off;

-- Draft of DDL scripts for CGEMS, generated on 9/20/2006


CREATE TABLE CHR_START_END
(
  CHROMOSOME      VARCHAR2(2),
  START_LOCATION  NUMBER,
  END_LOCATION    NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE DNA_SPECIMEN
(
  DNA_MATERIAL_TYPE       VARCHAR2(50),
  DNA_EXTRACTION_METHOD   VARCHAR2(100),
  DNA_AMPLICATION_METHOD  VARCHAR2(20),
  SPECIMEN_ID             VARCHAR2(50)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE GENE_ALIAS
(
  ALIAS    VARCHAR2(200),
  GENE_ID  VARCHAR2(20)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE GENE_DIM
(
  GENE_ID             VARCHAR2(20),
  FEATURE_NAME        VARCHAR2(100),
  CHROMOSOME          VARCHAR2(8),
  CHROMOSOME_START    NUMBER,
  CHROMOSOME_END      NUMBER,
  ORIENTATION         VARCHAR2(20),
  CONTIG              VARCHAR2(20),
  CONTIG_START        NUMBER,
  CONTIG_END          NUMBER,
  CONTIG_ORIENTATION  VARCHAR2(20),
  FEATURE_TYPE        VARCHAR2(20),
  SUBMIT_GROUP        VARCHAR2(20),
  TRANSCRIPT          VARCHAR2(20),
  WEIGHT              NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE GENE_DIM_ALT
(
  GENE_ID           VARCHAR2(20),
  FEATURE_NAME      VARCHAR2(100),
  CHROMOSOME        VARCHAR2(8),
  CHROMOSOME_START  NUMBER,
  CHROMOSOME_END    NUMBER,
  ORIENTATION       VARCHAR2(20),
  ALT_START         NUMBER,
  ALT_END           NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE GENE_SNP_ASSO
(
  GENE_ID            VARCHAR2(20),
  FEATURE_NAME       VARCHAR2(100),
  SNPANNO_ID         VARCHAR2(50),
  DBSNPID            VARCHAR2(50),
  PHYSICAL_LOCATION  NUMBER(9),
  ALT_START          NUMBER,
  ALT_END            NUMBER,
  START_PHY          NUMBER,
  END_PHY            NUMBER,
  IND                NUMBER,
  ABS_DISTANCE       NUMBER,
  SNPANN_ID          NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE GENOTYPE_FACT
(
  GS_ID          NUMBER,
  ALLELE1        CHAR(1),
  ALLELE2        CHAR(1),
  QUALITY_SCORE  NUMBER(12,6),
  NORMAL_X       NUMBER(12,6),
  NORMAL_Y       NUMBER(12,6),
  RAW_X          NUMBER(12,6),
  RAW_Y          NUMBER(12,6),
  ASSAY_ID       NUMBER,
  SCAN_ID        NUMBER,
  SNPANNO_ID     VARCHAR2(50),
  STATUS         VARCHAR2(50),
  SPECIMEN_ID    VARCHAR2(50),
  STUDY_NAME     VARCHAR2(50)
)
NOLOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE GENOTYPE_STATUS_LU
(
  GENETYPE_STATUS  VARCHAR2(20)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE HISTOLOGY
(
  HISTOLOGY_ID           NUMBER                 NOT NULL,
  DIAGNOSIS_NAME         VARCHAR2(50),
  GRADE                  VARCHAR2(20),
  STAGE                  VARCHAR2(20),
  COMMENTS               VARCHAR2(200),
  TYPE                   VARCHAR2(200),
  INVASIVE_PRESENTATION  VARCHAR2(20)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE SNP_ANALYSIS_FINDING_FACT
(
  ASSO_ANA_FACT_ID  NUMBER                      NOT NULL,
  ASSO_ANA_PVALUE   NUMBER(12,6),
  ASSO_ANA_RANK     NUMBER,
  SNPANNO_ID        VARCHAR2(50),
  ASSO_ANALYSIS_ID  NUMBER,
  SNPANN_ID         NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE SNP_ANALYSIS_GROUP
(
  ANA_GRP_ID           NUMBER                   NOT NULL,
  ANA_GRP_NAME         VARCHAR2(100),
  ANA_GRP_DESCRIPTION  VARCHAR2(200),
  ASSO_ANALYSIS_ID     NUMBER,
  MEMBER_COUNT         NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE SNP_ASSAY
(
  ASSAY_ID         NUMBER                       NOT NULL,
  DESIGN_ALLELES   VARCHAR2(50),
  DESIGN_CODES     VARCHAR2(50),
  DESIGN_SCORE     NUMBER(8,2),
  DESIGN_SEQUENCE  VARCHAR2(2000),
  DESIGN_STRAND    CHAR(5),
  STATUS           VARCHAR2(50),
  VENDOR_ASSAY_ID  VARCHAR2(50),
  TECHNOLOGY       VARCHAR2(50),
  SNPANNO_ID       VARCHAR2(50),
  SNP_PANEL_ID     NUMBER,
  VERSION          VARCHAR2(20),
  SNPANN_ID        NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE SNP_ASSOCIATION_ANALYSIS
(
  ASSO_ANALYSIS_ID           NUMBER             NOT NULL,
  ASSO_ANALYSIS_NAME         VARCHAR2(50),
  ASSO_ANALYSIS_METHODS      VARCHAR2(50),
  ASSO_ANALYSIS_DESCRIPTION  VARCHAR2(200)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE SNP_DIM
(
  SNPANNO_ID          VARCHAR2(50)              NOT NULL,
  CHROMOSOME          VARCHAR2(6),
  PHYSICAL_LOCATION   NUMBER(9),
  DBSNP_BUILD         VARCHAR2(25),
  DBSNPID             VARCHAR2(50),
  GENOME_BUILD        VARCHAR2(25),
  REFERENCE_SEQUENCE  VARCHAR2(2000),
  REFERENCE_STRAND    CHAR(5),
  SNPANN_ID           NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE SNP_FREQUENCY_FACT
(
  SNP_FREQ_ID                 NUMBER(12)        NOT NULL,
  HARDYWEINBERG_P_VALUE       NUMBER(12,6),
  HETEROZYGOTE_COUNT          NUMBER(8),
  MISSING_ALLELE_FREQ         NUMBER(12,6),
  MISSING_ALLELE_COUNT        NUMBER(8),
  MISSSING_GENOTYPE_COUNT     NUMBER(8),
  OTHER_ALLELE                CHAR(1),
  OTHER_ALLELE_COUNT          NUMBER(8),
  OTHER_HOMOZYGOTE_COUNT      NUMBER(8),
  REFERENCE_ALLELE            CHAR(1)           NOT NULL,
  REFERENCE_ALLELE_COUNT      NUMBER(8),
  REFERENCE_HOMOZYGOTE_COUNT  NUMBER(8),
  SNPANNO_ID                  VARCHAR2(50)      NOT NULL,
  POPULATION_ID               NUMBER,
  COMPLETION_RATE             NUMBER(12,6),
  MINOR_ALLELE_FREQ           NUMBER(12,6),
  SNPANN_ID                   NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE SNP_PANEL
(
  SNP_PANEL_ID       NUMBER                     NOT NULL,
  SNP_PANEL_NAME     VARCHAR2(50),
  TECHNOLOGY         VARCHAR2(100),
  PANEL_DESCRIPTION  VARCHAR2(200),
  VENDOR             VARCHAR2(50),
  VENDOR_PANEL_ID    VARCHAR2(30),
  VERSION            VARCHAR2(20),
  ASSAY_COUNT        NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE SPECIMEN
(
  SPECIMEN_ID        VARCHAR2(50)               NOT NULL,
  SPECIMEN_TYPE      VARCHAR2(50),
  COLLECTION_METHOD  VARCHAR2(100),
  PARTICIPANT_DID    VARCHAR2(50),
  TIMECOURSE_NAME    VARCHAR2(50),
  DISEASE_NAME       VARCHAR2(50),
  DISEASE_GRADE      VARCHAR2(50),
  INSTITUTION_ID     NUMBER,
  TIMECOURSE_ID      NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE STDPT_ANALYSIS_GRP_AS
(
  ANA_GRP_ID       NUMBER                       NOT NULL,
  PARTICIPANT_DID  VARCHAR2(50)                 NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE STUDY_DIM
(
  STUDY_NAME         VARCHAR2(50)               NOT NULL,
  STUDY_DESCRIPTION  VARCHAR2(200),
  START_DATE         DATE,
  END_DATE           DATE,
  STUDY_SPONSOR      VARCHAR2(100)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE STUDY_PANEL_ASSO
(
  STUDY_NAME    VARCHAR2(50)                    NOT NULL,
  SNP_PANEL_ID  NUMBER                          NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE STUDY_PARTICIPANT
(
  PARTICIPANT_DID       VARCHAR2(50)            NOT NULL,
  AGE_AT_DIAGNOSIS      NUMBER,
  AGE_AT_ENROLL         NUMBER,
  AGE_AT_DEATH          NUMBER,
  DAYS_ON_STUDY         NUMBER,
  ETHNIC_GROUP_CODE     VARCHAR2(50),
  RACE_CODE             VARCHAR2(50),
  GENDER                VARCHAR2(50),
  SURVIVAL_STATUS       CHAR(1),
  INSTITUTION_NAME      VARCHAR2(50),
  STUDY_NAME            VARCHAR2(50),
  OFF_STUDY             CHAR(1),
  DAYS_OFF_STUDY        NUMBER,
  POPULATION_ID         NUMBER,
  FAMILY_HISTORY        VARCHAR2(200),
  CASE_CONTROL_STATUS   VARCHAR2(20),
  AGE_AT_DIAGNOSIS_MIN  NUMBER,
  AGE_AT_DIAGNOSIS_MAX  NUMBER,
  AGE_AT_ENROLL_MIN     NUMBER,
  AGE_AT_ENROLL_MAX     NUMBER,
  AGE_AT_DEATH_MIN      NUMBER,
  AGE_AT_DEATH_MAX      NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE STUDY_POPULATION
(
  POPULATION_ID    NUMBER                       NOT NULL,
  POPULATION_NAME  VARCHAR2(50),
  POPULATION_DESC  VARCHAR2(200),
  SOURCE           VARCHAR2(100),
  MEMBER_COUNT     NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE STUDY_STDPOPUPLATION_ASSO
(
  STUDY_NAME     VARCHAR2(50)                   NOT NULL,
  POPULATION_ID  NUMBER                         NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE STUDY_TIMECOURSE_DIM
(
  TIMECOURSE_ID    NUMBER                       NOT NULL,
  TIMECOURSE_NAME  VARCHAR2(50),
  TIMECOURSE_DESC  VARCHAR2(200)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE INDEX CHR_START_END_CHR_IDX ON CHR_START_END
(CHROMOSOME)
LOGGING
NOPARALLEL;


CREATE INDEX GENE_ALIAS_ALIAS_IDX ON GENE_ALIAS
(ALIAS)
NOLOGGING
NOPARALLEL;


CREATE INDEX GENE_ALIAS_GENEID_IDX ON GENE_ALIAS
(GENE_ID)
NOLOGGING
NOPARALLEL;


CREATE INDEX GENE_DIM_GENENM_IDX ON GENE_DIM
(FEATURE_NAME)
LOGGING
NOPARALLEL;


CREATE INDEX GENE_ID_CHROM_IDX ON GENE_DIM
(CHROMOSOME)
LOGGING
NOPARALLEL;


CREATE INDEX GENE_ID_GENEID_IDX ON GENE_DIM
(GENE_ID)
LOGGING
NOPARALLEL;


CREATE INDEX GENE_SNP_ASSO_DBSNPID_IDX ON GENE_SNP_ASSO
(DBSNPID)
LOGGING
NOPARALLEL;


CREATE INDEX GENE_SNP_ASSO_GENEID_IDX ON GENE_SNP_ASSO
(GENE_ID)
LOGGING
NOPARALLEL;


CREATE INDEX GENE_SNP_ASSO_GENENM_IDX ON GENE_SNP_ASSO
(FEATURE_NAME)
LOGGING
NOPARALLEL;


CREATE INDEX GENE_SNP_ASSO_PHYLOC_IDX ON GENE_SNP_ASSO
(PHYSICAL_LOCATION)
LOGGING
NOPARALLEL;


CREATE INDEX GENE_SNP_ASSO_SNPID_IDX ON GENE_SNP_ASSO
(SNPANNO_ID)
LOGGING
NOPARALLEL;


CREATE BITMAP INDEX GENOTYPE_FACT_PT_BIDX ON GENOTYPE_FACT
(SPECIMEN_ID)
LOGGING
NOPARALLEL;


CREATE BITMAP INDEX GENOTYPE_FACT_QC_BIDX ON GENOTYPE_FACT
(STATUS)
LOGGING
NOPARALLEL;


CREATE INDEX GENOTYPE_FACT_SNPANNID_IDX ON GENOTYPE_FACT
(SNPANNO_ID)
LOGGING
NOPARALLEL;


CREATE INDEX SNAPASSAY_SNPANID_IDX ON SNP_ASSAY
(SNPANNO_ID)
NOLOGGING
NOPARALLEL;


CREATE INDEX SNPDIM_DBSNPID_IDX ON SNP_DIM
(DBSNPID)
NOLOGGING
NOPARALLEL;


CREATE INDEX SNPDM_CHR_IDX ON SNP_DIM
(CHROMOSOME)
NOLOGGING
NOPARALLEL;


CREATE BITMAP INDEX SNP_ANA_FF_ASSOANAID_BIDX ON SNP_ANALYSIS_FINDING_FACT
(ASSO_ANALYSIS_ID)
LOGGING
NOPARALLEL;


CREATE INDEX SNP_ANA_FF_ASSOPV_IDX ON SNP_ANALYSIS_FINDING_FACT
(ASSO_ANA_PVALUE)
LOGGING
NOPARALLEL;


CREATE INDEX SNP_ANA_FF_RANK_IDX ON SNP_ANALYSIS_FINDING_FACT
(ASSO_ANA_RANK)
LOGGING
NOPARALLEL;


CREATE INDEX SNP_ANA_FF_SNPID_IDX ON SNP_ANALYSIS_FINDING_FACT
(SNPANNO_ID)
LOGGING
NOPARALLEL;


CREATE BITMAP INDEX SNP_ASSAY_PANELID_BIDX ON SNP_ASSAY
(SNP_PANEL_ID)
LOGGING
NOPARALLEL;


CREATE INDEX SNP_ASSO_ANALYSIS_NM_IDX ON SNP_ASSOCIATION_ANALYSIS
(ASSO_ANALYSIS_NAME)
NOLOGGING
NOPARALLEL;


CREATE INDEX SNP_DIM_PHYLOC_IDX ON SNP_DIM
(PHYSICAL_LOCATION)
LOGGING
NOPARALLEL;


CREATE BITMAP INDEX SNP_DIM_REFSTRAND_BIDX ON SNP_DIM
(REFERENCE_STRAND)
LOGGING
NOPARALLEL;


CREATE INDEX SNP_FREQ_FACT_COMRT_IDX ON SNP_FREQUENCY_FACT
(COMPLETION_RATE)
LOGGING
NOPARALLEL;


CREATE INDEX SNP_FREQ_FACT_HWP_IDX ON SNP_FREQUENCY_FACT
(HARDYWEINBERG_P_VALUE)
LOGGING
NOPARALLEL;


CREATE INDEX SNP_FREQ_FACT_MINAFREQ_IDX ON SNP_FREQUENCY_FACT
(MINOR_ALLELE_FREQ)
LOGGING
NOPARALLEL;


CREATE BITMAP INDEX SNP_FREQ_FACT_OTAL_BIDX ON SNP_FREQUENCY_FACT
(OTHER_ALLELE)
NOLOGGING
NOPARALLEL;


CREATE BITMAP INDEX SNP_FREQ_FACT_POPUID_BIDX ON SNP_FREQUENCY_FACT
(POPULATION_ID)
NOLOGGING
NOPARALLEL;


CREATE BITMAP INDEX SNP_FREQ_FACT_RFAL_BIDX ON SNP_FREQUENCY_FACT
(REFERENCE_ALLELE)
NOLOGGING
NOPARALLEL;


CREATE INDEX SNP_FREQ_FACT_SNPANID_IDX ON SNP_FREQUENCY_FACT
(SNPANNO_ID)
NOLOGGING
NOPARALLEL;


CREATE INDEX SNP_PANEL_PANNM_IDX ON SNP_PANEL
(SNP_PANEL_NAME)
NOLOGGING
NOPARALLEL;


CREATE INDEX SPECIMEN_PTDID_IDX ON SPECIMEN
(PARTICIPANT_DID)
NOLOGGING
NOPARALLEL;


CREATE INDEX STD_PARTICIPANT_AGEENMAX_IDX ON STUDY_PARTICIPANT
(AGE_AT_DIAGNOSIS_MAX)
LOGGING
NOPARALLEL;


CREATE INDEX STD_PARTICIPANT_AGEENMIN_IDX ON STUDY_PARTICIPANT
(AGE_AT_ENROLL_MIN)
LOGGING
NOPARALLEL;


CREATE BITMAP INDEX STD_PARTICIPANT_FMHIX_BIDX ON STUDY_PARTICIPANT
(FAMILY_HISTORY)
LOGGING
NOPARALLEL;


CREATE BITMAP INDEX STD_PARTICIPANT_GENDER_BIDX ON STUDY_PARTICIPANT
(GENDER)
LOGGING
NOPARALLEL;


CREATE BITMAP INDEX STD_PARTICIPANT_POPID_BIDX ON STUDY_PARTICIPANT
(POPULATION_ID)
LOGGING
NOPARALLEL;


CREATE BITMAP INDEX STD_PARTICIPANT_RACE_BIDX ON STUDY_PARTICIPANT
(RACE_CODE)
LOGGING
NOPARALLEL;


CREATE BITMAP INDEX STD_PARTICIPANT_STDNM_BIDX ON STUDY_PARTICIPANT
(STUDY_NAME)
LOGGING
NOPARALLEL;


CREATE INDEX STUDY_POPULATION_POPUNM_IDX ON STUDY_POPULATION
(POPULATION_NAME)
NOLOGGING
NOPARALLEL;


ALTER TABLE HISTOLOGY ADD (
  PRIMARY KEY (HISTOLOGY_ID));


ALTER TABLE SNP_ANALYSIS_FINDING_FACT ADD (
  PRIMARY KEY (ASSO_ANA_FACT_ID));


ALTER TABLE SNP_ANALYSIS_GROUP ADD (
  PRIMARY KEY (ANA_GRP_ID));


ALTER TABLE SNP_ASSAY ADD (
  PRIMARY KEY (ASSAY_ID));


ALTER TABLE SNP_ASSOCIATION_ANALYSIS ADD (
  PRIMARY KEY (ASSO_ANALYSIS_ID));


ALTER TABLE SNP_DIM ADD (
  PRIMARY KEY (SNPANNO_ID));


ALTER TABLE SNP_FREQUENCY_FACT ADD (
  PRIMARY KEY (SNP_FREQ_ID));


ALTER TABLE SNP_PANEL ADD (
  PRIMARY KEY (SNP_PANEL_ID));


ALTER TABLE SPECIMEN ADD (
  PRIMARY KEY (SPECIMEN_ID));


ALTER TABLE STDPT_ANALYSIS_GRP_AS ADD (
  PRIMARY KEY (ANA_GRP_ID, PARTICIPANT_DID));


ALTER TABLE STUDY_DIM ADD (
  PRIMARY KEY (STUDY_NAME));


ALTER TABLE STUDY_PANEL_ASSO ADD (
  PRIMARY KEY (STUDY_NAME, SNP_PANEL_ID));


ALTER TABLE STUDY_PARTICIPANT ADD (
  PRIMARY KEY (PARTICIPANT_DID));


ALTER TABLE STUDY_POPULATION ADD (
  PRIMARY KEY (POPULATION_ID));


ALTER TABLE STUDY_STDPOPUPLATION_ASSO ADD (
  PRIMARY KEY (STUDY_NAME, POPULATION_ID));


ALTER TABLE STUDY_TIMECOURSE_DIM ADD (
  PRIMARY KEY (TIMECOURSE_ID));


ALTER TABLE DNA_SPECIMEN ADD (
  FOREIGN KEY (SPECIMEN_ID) 
    REFERENCES SPECIMEN (SPECIMEN_ID)
    ON DELETE SET NULL);


ALTER TABLE GENOTYPE_FACT ADD (
  FOREIGN KEY (STUDY_NAME) 
    REFERENCES STUDY_DIM (STUDY_NAME)
    ON DELETE SET NULL DISABLE);

ALTER TABLE GENOTYPE_FACT ADD (
  FOREIGN KEY (ASSAY_ID) 
    REFERENCES SNP_ASSAY (ASSAY_ID)
    ON DELETE SET NULL DISABLE);

ALTER TABLE GENOTYPE_FACT ADD (
  FOREIGN KEY (SNPANNO_ID) 
    REFERENCES SNP_DIM (SNPANNO_ID)
    ON DELETE SET NULL DISABLE);

ALTER TABLE GENOTYPE_FACT ADD (
  FOREIGN KEY (SPECIMEN_ID) 
    REFERENCES SPECIMEN (SPECIMEN_ID)
    ON DELETE SET NULL DISABLE);


ALTER TABLE SNP_ANALYSIS_FINDING_FACT ADD (
  FOREIGN KEY (ASSO_ANALYSIS_ID) 
    REFERENCES SNP_ASSOCIATION_ANALYSIS (ASSO_ANALYSIS_ID)
    ON DELETE SET NULL);

ALTER TABLE SNP_ANALYSIS_FINDING_FACT ADD (
  FOREIGN KEY (SNPANNO_ID) 
    REFERENCES SNP_DIM (SNPANNO_ID)
    ON DELETE SET NULL);


ALTER TABLE SNP_ANALYSIS_GROUP ADD (
  FOREIGN KEY (ASSO_ANALYSIS_ID) 
    REFERENCES SNP_ASSOCIATION_ANALYSIS (ASSO_ANALYSIS_ID)
    ON DELETE SET NULL);


ALTER TABLE SNP_ASSAY ADD (
  FOREIGN KEY (SNPANNO_ID) 
    REFERENCES SNP_DIM (SNPANNO_ID)
    ON DELETE SET NULL);

ALTER TABLE SNP_ASSAY ADD (
  FOREIGN KEY (SNP_PANEL_ID) 
    REFERENCES SNP_PANEL (SNP_PANEL_ID)
    ON DELETE SET NULL);


ALTER TABLE SNP_FREQUENCY_FACT ADD (
  FOREIGN KEY (POPULATION_ID) 
    REFERENCES STUDY_POPULATION (POPULATION_ID)
    ON DELETE SET NULL);

ALTER TABLE SNP_FREQUENCY_FACT ADD (
  FOREIGN KEY (SNPANNO_ID) 
    REFERENCES SNP_DIM (SNPANNO_ID)
    ON DELETE SET NULL);


ALTER TABLE SPECIMEN ADD (
  FOREIGN KEY (TIMECOURSE_ID) 
    REFERENCES STUDY_TIMECOURSE_DIM (TIMECOURSE_ID)
    ON DELETE SET NULL);

ALTER TABLE SPECIMEN ADD (
  FOREIGN KEY (PARTICIPANT_DID) 
    REFERENCES STUDY_PARTICIPANT (PARTICIPANT_DID)
    ON DELETE SET NULL);


ALTER TABLE STDPT_ANALYSIS_GRP_AS ADD (
  FOREIGN KEY (PARTICIPANT_DID) 
    REFERENCES STUDY_PARTICIPANT (PARTICIPANT_DID)
    ON DELETE SET NULL);

ALTER TABLE STDPT_ANALYSIS_GRP_AS ADD (
  FOREIGN KEY (ANA_GRP_ID) 
    REFERENCES SNP_ANALYSIS_GROUP (ANA_GRP_ID)
    ON DELETE SET NULL);


ALTER TABLE STUDY_PANEL_ASSO ADD (
  FOREIGN KEY (SNP_PANEL_ID) 
    REFERENCES SNP_PANEL (SNP_PANEL_ID)
    ON DELETE SET NULL);

ALTER TABLE STUDY_PANEL_ASSO ADD (
  FOREIGN KEY (STUDY_NAME) 
    REFERENCES STUDY_DIM (STUDY_NAME)
    ON DELETE SET NULL);


ALTER TABLE STUDY_PARTICIPANT ADD (
  FOREIGN KEY (POPULATION_ID) 
    REFERENCES STUDY_POPULATION (POPULATION_ID)
    ON DELETE SET NULL);

ALTER TABLE STUDY_PARTICIPANT ADD (
  FOREIGN KEY (STUDY_NAME) 
    REFERENCES STUDY_DIM (STUDY_NAME)
    ON DELETE SET NULL);


ALTER TABLE STUDY_STDPOPUPLATION_ASSO ADD (
  FOREIGN KEY (POPULATION_ID) 
    REFERENCES STUDY_POPULATION (POPULATION_ID)
    ON DELETE SET NULL);

ALTER TABLE STUDY_STDPOPUPLATION_ASSO ADD (
  FOREIGN KEY (STUDY_NAME) 
    REFERENCES STUDY_DIM (STUDY_NAME)
    ON DELETE SET NULL);

spool off;

