/*L
  Copyright Duke Comprehensive Cancer Center

  Distributed under the OSI-approved BSD 3-Clause License.
  See http://ncip.github.com/catrip/LICENSE.txt for details.
L*/

CREATE TABLE SPECIMEN
(
  ANNOTATABLE_ENTITY_ID  NUMBER(20)             NOT NULL,
  ACCESSION_ID           NUMBER(20),
  PARENT_SPECIMEN_ID     NUMBER(20),
  SURGICAL_LABEL         VARCHAR2(200 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX SPEC_ANNO_ENT_ID_PK ON SPECIMEN
(ANNOTATABLE_ENTITY_ID)
LOGGING
NOPARALLEL;


ALTER TABLE SPECIMEN ADD (
  CONSTRAINT SPEC_ANNO_ENT_ID_PK PRIMARY KEY (ANNOTATABLE_ENTITY_ID));



