/*L
  Copyright Duke Comprehensive Cancer Center

  Distributed under the OSI-approved BSD 3-Clause License.
  See http://ncip.github.com/catrip/LICENSE.txt for details.
L*/

INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
1, 'DU200'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
2, 'DU300'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
2, 'DU400'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
3, 'DU500'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
4, 'DU600'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
3, 'DU700'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
4, 'DU800'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
5, 'DU900'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
5, 'DU1000'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
6, 'DU1100'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
7, 'DU1200'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
6, 'DU1300'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
7, 'DU1400'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
8, 'DU1500'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
8, 'DU1600'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
8, 'DU1700'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
9, 'DU1800'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
10, 'DU1900'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
10, 'DU2000'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
10, 'DU2100'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
10, 'DU2200'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
11, 'DU2300'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
11, 'DU2400'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
11, 'DU2500'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
11, 'DU2600'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
11, 'DU2700'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
11, 'DU2800'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
11, 'DU2900'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
11, 'DU3000'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
11, 'DU3100'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
1, 'DU3200'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
1, 'DU3300'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
1, 'DU3400'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
1, 'DU3500'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
1, 'DU3600'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
1, 'DU3700'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
1, 'DU3800'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
1, 'DU3900'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
5, 'DU4000'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
5, 'TT4100'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
5, 'TT4200'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
12, 'TT4300'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
12, 'TT4400'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
12, 'TT4500'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
12, 'TT4600'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
12, 'TT4700'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
12, 'TT4800'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
12, 'TT4900'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
12, 'TT5000'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
12, 'TT5100'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
12, 'TT5200'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
4, 'TT5300'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
4, 'TT5400'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
4, 'TT5500'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
4, 'TT5600'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
4, 'TT5700'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
4, 'TT5800'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
4, 'TT5900'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
4, 'TT6000'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
4, 'TT6100'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
4, 'TT6200'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
4, 'TT6300'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
4, 'TT6400'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
4, 'TT6500'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
4, 'TT6600'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
4, 'TT6700'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
6, 'TT6800'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
6, 'TT6900'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
6, 'TT7000'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
6, 'TT7100'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
6, 'TT7200'); 
INSERT INTO STDPT_ANALYSIS_GRP_AS ( ANA_GRP_ID, PARTICIPANT_DID ) VALUES ( 
1, 'DU100'); 
commit;
 
