package gov.nih.nci.cagrid.caecae.service.globus;

import gov.nih.nci.cagrid.caecae.service.CAECAEImpl;

import java.rmi.RemoteException;

/** 
 *  DO NOT EDIT:  This class is autogenerated!
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class CAECAEProviderImpl{
	
	CAECAEImpl impl;
	
	public CAECAEProviderImpl() throws RemoteException {
		impl = new CAECAEImpl();
	}
	

}
