package gov.nih.nci.cagrid.cae.service.globus;

import gov.nih.nci.cagrid.cae.service.CAEImpl;

import java.rmi.RemoteException;

/** 
 *  DO NOT EDIT:  This class is autogenerated!
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class CAEProviderImpl{
	
	CAEImpl impl;
	
	public CAEProviderImpl() throws RemoteException {
		impl = new CAEImpl();
	}
	
	protected String getCallerIdentity() {
		String caller = org.globus.wsrf.security.SecurityManager.getManager().getCaller();
		if ((caller == null) || (caller.equals("<anonymous>"))) {
			return null;
		} else {
			return caller;
		}
	}
	

}
