package gov.nih.nci.cagrid.catissuecorefull.service.globus;

import gov.nih.nci.cagrid.catissuecorefull.service.CaTissueCore_FullImpl;

import java.rmi.RemoteException;

/** 
 *  DO NOT EDIT:  This class is autogenerated!
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class CaTissueCore_FullProviderImpl{
	
	CaTissueCore_FullImpl impl;
	
	public CaTissueCore_FullProviderImpl() throws RemoteException {
		impl = new CaTissueCore_FullImpl();
	}
	

}
