/*L
  Copyright Duke Comprehensive Cancer Center

  Distributed under the OSI-approved BSD 3-Clause License.
  See http://ncip.github.com/catrip/LICENSE.txt for details.
L*/

--  ------------------------------------------- 
--  Generated by Enterprise Architect Ver. 4.01
--  Created On : Monday, 18 September, 2006 
--  DBMS       : Oracle 
--  ------------------------------------------- 

DROP TABLE ACTIVITY_SUMMARY CASCADE CONSTRAINTS;

CREATE TABLE ACTIVITY_SUMMARY ( 
	ID NUMBER(8) NOT NULL,
	LOCAL_DATE DATE,
	SUMMARY_DATE DATE,
	LOCAL_CHARACTERIZATION VARCHAR2(100),
	SUMMARY_CHARACTERIZATION VARCHAR2(100)
) 
;

ALTER TABLE ACTIVITY_SUMMARY ADD CONSTRAINT PK_ACTIVITY_SUMMARY 
PRIMARY KEY (ID) 
;

-- ALTER TABLE ACTIVITY_SUMMARY ADD CONSTRAINT FK_ACTIVITY_SUMMARY_DIAGNOSIS 
-- FOREIGN KEY (ID) REFERENCES DIAGNOSIS (ID);








